### ISSUE TITLE
[QUESTION] juicefs csi driver 是否支持平滑升级

### ISSUE THREAD

**Issue by SonglinLife** [juicedata/juicefs-csi-driver#1009]
## Question

我注意到jfs的公众号，在4月份的时候发布了这么一篇文章。JuiceFS v1.2-beta1：[平滑升级功能详解，不停服即可更新](https://mp.weixin.qq.com/s/Cxkv3105EBp7g2hjedR-aQ)，更新的juicefs客户端通过接管旧的客户端的mount fd实现平滑升级。

但是我在jfs csi文档中，找到这样的描述。

> 升级 CSI 驱动，会伴随着 JuiceFS 客户端（也就是 mount 镜像）的升级，不过不用担心，正在运行的 mount pod 并不受影响，应用滚升或重建以后才会生效。

似乎csi driver没有支持这个功能，我想了解社区有把这个功能添加到csi的计划吗？

**Comment by zwwhdls** [comment]
在计划中

**Comment by SonglinLife** [comment]
期待你们的工作
