### ISSUE TITLE
[QUESTION]  Dashboard GUI does not display data

### ISSUE THREAD

**Issue by KKulishov** [juicedata/juicefs-csi-driver#1024]
## Dashboard GUI does not display data

Hello. In helm charts in deployment dashboard [this](https://github.com/juicedata/charts/blob/main/charts/juicefs-csi-driver/templates/deployment.yaml) 

if  deploy. And go to https gui

![dashboard-app](https://github.com/juicedata/juicefs-csi-driver/assets/21700458/7f23a002-b898-4887-a20d-312e3cb28b89)

![dashboard-sc](https://github.com/juicedata/juicefs-csi-driver/assets/21700458/0dbc528c-e43d-4c87-a86d-2524594a8e1d)
 
in logs Dashboard 

```
E0705 08:35:49.020937 1 controller.go:68] get pod zzz-xxxx-backend-test/backend-schedule-1720168380-cnjzv failed: Pod "backend-schedule-1720168380-cnjzv" not found
E0705 08:35:51.217540 1 controller.go:68] get pod telegram-integration-test/telegram-integration-celery-worker-55599b4cb5-674mj failed: Pod "telegram-integration-celery-worker-55599b4cb5-674mj" not found
E0705 08:35:55.849111 1 controller.go:68] get pod telegram-integration-test/telegram-integration-rbsbot-5f5dd8f777-d6r94 failed: Pod "telegram-integration-rbsbot-5f5dd8f777-d6r94" not found
E0705 08:35:56.138071 1 controller.go:68] get pod telegram-integration-test/telegram-integration-celery-beat-7b986745d8-4vhj7 failed: Pod "telegram-integration-celery-beat-7b986745d8-4vhj7" not found
```

he goes to different pods in which others storage class 

But pv/pvc for storage class  are being created and exist.

Can you tell me why it is not displayed pv/pvc for storage class  csi.juicefs.com?

- Kuber  version 1.20 
- juicedata/juicefs-csi-driver:v0.24.2
- juicedata/csi-dashboard:v0.24.2

**Comment by zxh326** [comment]
first install or upgrade？


if upgrade you need clean cache or force refresh website

**Comment by KKulishov** [comment]
Yes, you are right. Cache in chrome, after clearing everything is fine
