### ISSUE TITLE
[BUG] csi dashboard 无法识别对应的mount pod

### ISSUE THREAD

**Issue by luoxingit** [juicedata/juicefs-csi-driver#1066]
![image](https://github.com/user-attachments/assets/60cbc87a-7bb4-40a3-ba00-a2095ac24aee)

**Comment by luoxingit** [comment]
复现版本
v0.24.4
v0.24.1

**Comment by zwwhdls** [comment]
closed by https://github.com/juicedata/juicefs-csi-driver/pull/1064
