### ISSUE TITLE
[BUG] 批量升级相关问题

### ISSUE THREAD

**Issue by YunhuiChen** [juicedata/juicefs-csi-driver#1198]
**What happened**:

1、修改配置保存后立即生效按钮经常无法点击
2、批量升级开始升级以后，状态会一直卡在升级过程中
3、修改配置并保存，然后再修改配置再保存，第二次修改的配置会被丢失
4、2024-12-03 09:34:49 BATCH-FAIL some pods upgrade failed  打印一下所有失败的mount pod

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by YunhuiChen** [comment]
5、开启跳过失败失败任务时，有失败直接跳出了完成按钮，任务还在继续
<img width="1419" alt="截屏2024-12-04 18 10 28" src="https://github.com/user-attachments/assets/b2a7e54d-10f5-4535-ab3d-05e4afb3af29">

**Comment by zwwhdls** [comment]
fixed by https://github.com/juicedata/juicefs-csi-driver/pull/1175
