### ISSUE TITLE
[FEATURE] deprecate old k8s apis

### ISSUE THREAD

**Issue by timfeirg** [juicedata/juicefs-csi-driver#1200]
deprecate old APIs and switch to their newer version

<img width="833" alt="image" src="https://github.com/user-attachments/assets/016aded2-6d71-411b-b9fa-235811726cf9">

**Comment by zxh326** [comment]
After this [PR](https://github.com/juicedata/juicefs-csi-driver/pull/1168) (not released yet), the deprecate APIs should not be used.
