### ISSUE TITLE
[QUESTION] 是否可以在juicefs-csi-driver 使用 juicefs clone

### ISSUE THREAD

**Issue by mashangxiu** [juicedata/juicefs-csi-driver#1211]
**What help did you want**:

       我希望能够在使用k8s数据卷的容器中使用juicefs clone 进行快速的文件clone 但是我使用的时候出现 2024/12/16 19:04:13.445671 juicefs[179] <FATAL>: xxxx  is not inside JuiceFS [main.go:31]
       是否有方式能够在csi里面使用clone呢

**Comment by zxh326** [comment]
试试在 mountpod 里 clone
