### ISSUE TITLE
Metadata and data in the object storage should be automatically cleaned up after deleting pvc and pv

### ISSUE THREAD

**Issue by aland-zhang** [juicedata/juicefs-csi-driver#196]
I found a problem with juicefs-csi-driver today. Create a pvc and bind it to a pod application，the PV id is “pvc-d7562c2d-a68c-4ca4-b012-b5772a2eebf5”, write files, then stop the pod, after deleting pvc, pv will continue to create pvc regardless of Retain or delete state, the new PV id is "pvc-c53e25e6-8004-4444-b6c6-2a2726cce4f0",and continue to bind to a pod for use, and find /var/lib/juicefs/volume/pvc-c53e25e6-8004-4444-b6c6-2a2726cce4f0  The newly created PV directory under the volume directory contains the old PV directory "pvc-d7562c2d-a68c-4ca4-b012-b5772a2eebf5" that was just deleted.
   I think the metadata and data are not cleaned up after deleting pvc and pv. When the RECLAIM POLICY of PV is Delete, when the PVC is deleted, the PV is automatically deleted and the data in the metadata and object storage should be cleaned up.
Also, when the RECLAIM POLICY of the PV is Retain, after deleting the PVC and manually deleting the PV, the metadata and data in the object storage should be automatically cleaned up.

**Comment by zwwhdls** [comment]
Hi @aland-zhang , which version is your juicefs csi driver?

**Comment by aland-zhang** [comment]
Driver: csi.juicefs.com version v0.10.6-13-g05de556 commit 05de5566f21abc1bfa240969220d9026a2cccf51 date 2021-11-12T00:15:20Z
I1115 13:52:45.849474       1 controller.go:48] Controller: JuiceFS version 4.5.7 (2021-11-08 87b548d)
I1115 13:52:46.343170       1 node.go:62] Node: JuiceFS version 4.5.7 (2021-11-08 87b548d)

**Comment by zwwhdls** [comment]
Hi @aland-zhang , can you provide logs of csi controller pod when the issue reproduced?

```
kubectl -n kube-system logs juicefs-csi-controller-0 juicefs-plugin
```

**Comment by aland-zhang** [comment]
juicefs  docker has been cleaned up, log is gone！![bugimage](https://github.com/aland-zhang/images/blob/main/2021-11-13_22-15-08.png)  see the image:https://github.com/aland-zhang/images/blob/main/2021-11-13_22-15-08.png

**Comment by zwwhdls** [comment]
Hi @aland-zhang , PV Retain policy will not deleteVolume even if PV is deleted. Please refer to https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain 

Closing.
