### ISSUE TITLE
The mount parameter of JuiceFS mount pod has not changed

### ISSUE THREAD

**Issue by aland-zhang** [juicedata/juicefs-csi-driver#203]
version: juicefs-csi-driver/v0.10.7
After modifying the mountOptions parameter cache-size in StorageClass and pv from 500 to 1000, the business container is not restarted, and the  JuiceFS mount pod juicefs-qsy05-pvc-c7f6e1c4-5c3d-4fc7-8955-63ffdebbedc5 container corresponding to the restart is forced to have the mount parameter unchanged. , Still the old 500 value.
/bin/mount.juicefs redis://xxxxx:6379/1 /jfs/pvc-c7f6e1c4-5c3d-4fc7-8955-63ffdebbedc5
       -o writeback,enable-xattr,max-uploads=60,cache-size=500 . It should be 1000.

When I restarted the business container, the cache-size of the JuiceFS mount pod mount parameter changed to 1000.
Because it is necessary to smoothly upgrade the mountOptions parameters, it would be unfriendly if the business container was restarted to update the mountOptions parameters.

**Comment by zwwhdls** [comment]
Hi @aland-zhang ,

When mount pod restart, it will reuse mount option before. It will use mount parameters in PV/StorageClass only when kubelet calls csi interface, in other words, when business container restarted.

**Comment by aland-zhang** [comment]
okay, got it. I just want to smoothly upgrade the mountOptions parameter.
