### ISSUE TITLE
Build for arm64

### ISSUE THREAD

**Issue by diseq** [juicedata/juicefs-csi-driver#225]
**What feature you'd like to add:**
a build for arm64 (kubernetes.io/arch=arm64) would be great to have.

**Why is this feature needed:**
increasing availability on providers

**Comment by zwwhdls** [comment]
JuiceFS CSI Driver support arm64. You can refer to https://github.com/juicedata/juicefs-csi-driver/blob/master/docs/en/csi-in-arm64.md

**Comment by diseq** [comment]
thanks. saw the arch appearing with tag v0.11.1

**Comment by stevefan1999-personal** [comment]
@zwwhdls please reopen, does not work on oracle cloud with exec format error. I even pulled the specific digest for arm64 of v0.13.0. seems like the buildbot is broken

**Comment by stevefan1999-personal** [comment]
0.11.1 seems working

**Comment by zwwhdls** [comment]
@stevefan1999-personal THX for reporting, I create a new issue : https://github.com/juicedata/juicefs-csi-driver/issues/284

**Comment by zwwhdls** [comment]
Hi @stevefan1999-personal , v0.13.1 is released, fixing tini in Dockerfile (https://github.com/juicedata/juicefs-csi-driver/pull/285). You can have a try.
