### ISSUE TITLE
[FEATURE] Does csi-driver support gc in a fixed time

### ISSUE THREAD

**Issue by lixuchun314** [juicedata/juicefs-csi-driver#237]
**What feature you'd like to add:csi-driver could gc in a fixed time**

**Why is this feature needed:file always in minio bucket  when umount pod and delete pvc,pv**

**Comment by zwwhdls** [comment]
Hi @lixuchun314 , 

CSI cannot trigger file deletion. You can use pv with delete ReclaimPolicy or make a crontab to do gc.

closing, thx
