### ISSUE TITLE
[BUG] CSI controller spawn zombie processes

### ISSUE THREAD

**Issue by zwwhdls** [juicedata/juicefs-csi-driver#246]
**What happened**:
Many zombie processes in node and its parent process is csi controller

```
$ ps -ef |grep juicefs
root     3385475 3385456  0 09:07 ?        00:00:00 /bin/juicefs-csi-driver --endpoint=unix:///var/lib/csi/sockets/pluginproxy/csi.sock --logtostderr --nodeid=$(NODE_ID) --v=5
root     3387535 3387512  0 09:07 ?        00:00:00 /bin/juicefs-csi-driver --endpoint=unix:/csi/csi.sock --logtostderr --nodeid=$(NODE_ID) --v=5 --enable-manager=true
root     3387673 3387651  0 09:07 ?        00:00:00 /csi-node-driver-registrar --csi-address=/csi/csi.sock --kubelet-registration-path=/var/lib/kubelet/csi-plugins/csi.juicefs.com/csi.sock --v=5
root     3422261 3422232  0 09:19 ?        00:00:00 sh -c /bin/mount.juicefs redis://10.96.118.10/0 /jfs/pvc-3b94d96d-5832-4114-b1dd-1f3d90b2e60a -o metrics=0.0.0.0:9567
root     3422281 3422261  0 09:19 ?        00:00:01 /bin/mount.juicefs redis://10.96.118.10/0 /jfs/pvc-3b94d96d-5832-4114-b1dd-1f3d90b2e60a -o metrics=0.0.0.0:9567
root     3443315 3385475  0 09:25 ?        00:00:00 [juicefs] <defunct>
root     3443321 3385475  0 09:25 ?        00:00:00 [juicefs] <defunct>
root     3445474 3385475  0 09:26 ?        00:00:00 [juicefs] <defunct>
root     3445502 3385475  0 09:26 ?        00:00:00 [juicefs] <defunct>
root     3447510 3385475  2 09:26 ?        00:00:00 [juicefs] <defunct>
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Create pod with PVC using storageClass.

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): v0.11.1
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by acechef** [comment]
After create a pvc, a zombie process will be generated?

**Comment by zwwhdls** [comment]
@acechef yes. That's because csi controller will mount and create subPath(which is pv volumeHandle), then juicefs mount process will be forked and be child process of init process. Init process in csi controller is juicefs-csi-controller which does not recycle child process resources. So mount process will be zombie process.

The solution is make [tini](https://github.com/krallin/tini) to be init process in container which will recycle child process resources.
