### ISSUE TITLE
[BUG]  helm install return an error 

### ISSUE THREAD

**Issue by ghost** [juicedata/juicefs-csi-driver#265]
i used helm install juicefs-csi-driver , it return an error about  converting YAML to JSON: yaml: line 18: could not find expected ':'

![image](https://user-images.githubusercontent.com/18397480/150952390-b4cbffdc-ff4e-4bef-8e08-8574f4ab25a4.png)

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):  lastest
- Kubernetes version (e.g. `kubectl version`):  v1.22.0
- Object storage (cloud provider and region): file
- Metadata engine info (version, cloud provider managed or self maintained): 
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): lcoal 
- Others:

**Comment by zwwhdls** [comment]
hi @IxaRyo , thanks for feedback, chart 0.8.1 has released, you can install 0.8.1
