### ISSUE TITLE
Support for Hashicorp Nomad

### ISSUE THREAD

**Issue by OmegaRogue** [juicedata/juicefs-csi-driver#270]
**What feature you'd like to add:**
Added support for running on [HashiCorp Nomad](https://www.nomadproject.io/)
**Why is this feature needed:**
Nomad supports the CSI specification and allows for a wider variety of workloads than kubernetes.
I have tried to run this driver on nomad, but the direct kubernetes dependencies are causing errors.

**Comment by davies** [comment]
The docs from Monad [1] says the K8S CSI driver work out of box with Monad, what the error you saw?

This CSI driver relies on k8S POD, does Monad has similar feature to manage containers?

[1] https://www.nomadproject.io/docs/internals/plugins/csi

**Comment by OmegaRogue** [comment]
On the controller allocation:
```
F0206 20:08:51.194502       8 main.go:50] Pod name & namespace can't be null.
```

On the node allocations:
```
Failed to start container c7d3a3b472de596fcc2c7986588f73bb6f7154c99a30f65d33c1f0e8f1ae31c2: API error (500): path /opt/nomad-client/data/client/csi/node/juicefs is mounted on / but it is not a shared mount
```
Nomad supports the Container Storage Interface, but not the kubernetes API, and this driver is explicitly dependant on both

**Comment by OmegaRogue** [comment]
Nomad manages a variety of different workloads, I'm running the allocations in Docker containers. This blog post outlines the similarities between kubernetes and nomad https://www.hashicorp.com/blog/a-kubernetes-user-s-guide-to-hashicorp-nomad

**Comment by OmegaRogue** [comment]
Any update on this?

**Comment by davies** [comment]
@OmegaRogue Can you try the versions before 0.10? Which may not use K8S API.

**Comment by OmegaRogue** [comment]
``
F0221 14:34:46.483746       1 main.go:47] nodeID must be provided
goroutine 1 [running]:
k8s.io/klog.stacks(0xc0001c5100, 0xc00017a500, 0x42, 0x98)
	/go/pkg/mod/k8s.io/klog@v0.1.0/klog.go:828 +0xb8
k8s.io/klog.(*loggingT).output(0xf92e20, 0xc000000003, 0xc0002644d0, 0xf2aecc, 0x7, 0x2f, 0x0)
	/go/pkg/mod/k8s.io/klog@v0.1.0/klog.go:779 +0x351
k8s.io/klog.(*loggingT).println(0xf92e20, 0xc000000003, 0xc0001e3f48, 0x1, 0x1)
	/go/pkg/mod/k8s.io/klog@v0.1.0/klog.go:656 +0xe7
k8s.io/klog.Fatalln(...)
	/go/pkg/mod/k8s.io/klog@v0.1.0/klog.go:1200
main.main()
	/juicefs-csi-driver/cmd/main.go:47 +0x316
```
they seem to also use the K8S API

**Comment by OmegaRogue** [comment]
Update: i managed to get it mostly working with 0.9.0, the error was due to not correctly putting in the flags for the driver. It now doesnt yet run on all of my clients because one of them is ARM64 and versions before 0.10.0 don't have arm builds available on dockerhub, but thats solved by manually building the image for arm

**Comment by davies** [comment]
@OmegaRogue Cool, what's the patch for 0.9.0 looks like? We should figure out a way to support Monad for future releases.

**Comment by OmegaRogue** [comment]
0.9.0 is the latest release that doesn't have any dependencies on the k8s api, and only on the csi api, which is why it is working

**Comment by ntreq** [comment]
When will the release with the nomad support be available?

**Comment by davies** [comment]
@ntreq it's still working in progress, we will add the docs when it's ready.

**Comment by zwwhdls** [comment]
Hi @OmegaRogue @ntreq , 

CSI nightly image is available for Nomad, you can refer to [the doc](https://github.com/juicedata/juicefs-csi-driver/blob/add_doc/docs/en/csi-in-nomad.md) and have a try.
