### ISSUE TITLE
[QUESTION]Dockerfile疑问

### ISSUE THREAD

**Issue by chen3** [juicedata/juicefs-csi-driver#297]
我看到csi的Dockerfile文件内从https://juicefs.com/static/juicefs 下载了二进制文件，想问下这个文件是闭源的还是开源的？

**Comment by zwwhdls** [comment]
Hi @chen3 , Dockerfile will download a `juicefs.py` script from https://juicefs.com/static/juicefs. This script will mount enterprise version of juicefs and is not open source.
