### ISSUE TITLE
[FEATURE] PVC Size limit.

### ISSUE THREAD

**Issue by swartz-k** [juicedata/juicefs-csi-driver#298]
**What feature you'd like to add:**
Will CSI support PVC size limit ?

I tried on k8s pod, PVC storage, such as 10Gi, will not work. With ref [docs](https://juicefs.com/docs/community/administration/quota), I think Juicefs can do it.
**Why is this feature needed:**

**Comment by zwwhdls** [comment]
Hi @swartz-k , This feature is in plan. Community edition of juicefs doesn't support capacity of subdirectory yet. However, CSI mount PV of StorageClass as subdirectory in pod. When juicefs community edition supports subdirectory capacity, we will support size limit asap. THX

**Comment by zwwhdls** [comment]
completed by https://github.com/juicedata/juicefs-csi-driver/pull/623

**Comment by breuerfelix** [comment]
@zwwhdls when are you going to release this one? :)

**Comment by zwwhdls** [comment]
@breuerfelix , sure, after juicefs v1.1 released since PVC capacity depends on it.
