### ISSUE TITLE
[FEATURE] PVs of the same storageClass should share the same mount pod

### ISSUE THREAD

**Issue by zwwhdls** [juicedata/juicefs-csi-driver#316]
**What feature you'd like to add:**

**Why is this feature needed:**

**Comment by holygrolli** [comment]
How is this feature being used? From looking over the source it seems to be enough to set env `STORAGE_CLASS_SHARE_MOUNT=true` but I did that and still every new pod using a PVC with same storageClass fires up a new mount pod like this:
```
pod_mount.go:303] createOrAddRef: Need to create pod juicefs-vmd96188-jfs-idrive-kraspf
pod_mount.go:303] createOrAddRef: Need to create pod juicefs-vmd96188-jfs-idrive-kwgnsn
```
any help much appreciated!
