### ISSUE TITLE
[BUG] Impossible to run on Nomad

### ISSUE THREAD

**Issue by tcassaert** [juicedata/juicefs-csi-driver#335]
**What happened**:
When trying to follow https://juicefs.com/docs/csi/csi-in-nomad/, it seems impossible to run the CSI driver outside of Kubernetes.
Getting:
```
8 driver.go:35] Can't get k8s client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
8 main.go:121] unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
```

**What you expected to happen**:
Being able to run the CSI driver on other container orchestrators.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the steps in the docs on a Nomad cluster.

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): nightly
- Kubernetes version (e.g. `kubectl version`): /
- Object storage (cloud provider and region): Irrelevant
- Metadata engine info (version, cloud provider managed or self maintained): Irrelevant
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): Irrelevant

**Comment by zwwhdls** [comment]
Hi @tcassaert , please check whether `"--by-process=true"` is added in csi-node args.

**Comment by tcassaert** [comment]
Hi @zwwhdls, it is enabled. I took the nomad job file from the docs, I just changed the `datacenter` to match my environment and the `id` of the `csi_plugin`:
```
job "jfs-controller" {
  datacenters = ["global"]
  type = "service"

  group "controller" {
    task "plugin" {
      driver = "docker"

      config {
        image = "juicedata/juicefs-csi-driver:nightly"

        args = [
          "--endpoint=unix://csi/csi.sock",
          "--logtostderr",
          "--nodeid=test",
          "--v=5",
          "--by-process=true",
        ]

        privileged = true
      }

      csi_plugin {
        id        = "juicefs"
        type      = "controller"
        mount_dir = "/csi"
      }

      resources {
        cpu    = 100
        memory = 512
      }
    }
  }
}
```

**Comment by zwwhdls** [comment]
Did it the same in `csi-node`? And can you change image to `v0.14.0` to have a try?

**Comment by tcassaert** [comment]
The `csi-node` and `csi-controller` both give the same error message, also on the `v0.14.0` image tag.

I'm not familiar with the code-base, but it looks like https://github.com/juicedata/juicefs-csi-driver/blob/master/pkg/driver/driver.go#L33 is being executed before the `--by-process` flag is evaluated?

**Comment by zwwhdls** [comment]
Sorry, we will fix asap
