### ISSUE TITLE
[FEATURE] Volume expansion

### ISSUE THREAD

**Issue by blampe** [juicedata/juicefs-csi-driver#345]
**What feature you'd like to add:**

https://github.com/container-storage-interface/spec/blob/release-1.6/spec.md#controllerexpandvolume

Currently, 
* modifying a JuiceFS PVC's storage request has no effect, and
* modifying the PVC's underlying PV causes mount failures:

```
MountVolume.MountDevice failed while expanding volume for volume "pvc-acb59dca-c2e2-40f6-9821-fa27d47dce0d" : Expander.NodeExpand found CSI plugin kubernetes.io/csi/csi.juicefs.com to not support node expansion
```

**Why is this feature needed:**

Dynamically resizing volumes is extremely helpful when expanding storage pools.

**Comment by aminmr** [comment]
Dear friends,
Any forecast for adding resizing to the JuiceFS CSI driver?
On the other hand, it should first support the size concept because whatever pvc size you provide, it is possible to create as much data on s3.
