### ISSUE TITLE
Insecure issue

### ISSUE THREAD

**Issue by showjason** [juicedata/juicefs-csi-driver#355]
Hi, I find that the password of meta address doesn't be encrypted, like below:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/27723125/174837347-10f76ad8-fe0b-4a9c-9bf8-10c72ee9cb89.png">
Is it necessary to encrypt it, like juicefs? If yes, let me try to fix it :D

**Comment by zwwhdls** [comment]
@showjason Thanks for pointing it out !  And contributions are welcome !

**Comment by showjason** [comment]
I'm sorry to be late to reply, the first idea comes to my mind is to reuse the function `RemovePassword` in juicefs util, and ignore the juice-csi-driver util, thus I wast a lot of time on testing 🙈. Big 👍 for your efficiency!
