### ISSUE TITLE
Generic Ephemeral Volumes support

### ISSUE THREAD

**Issue by Nick-0314** [juicedata/juicefs-csi-driver#367]
**What feature you'd like to add:**

Generic Ephemeral Volumes support
https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes

**Why is this feature needed:**

Generic Ephemeral Volumes support
https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes

Recently, I tested the https://github.com/actions-runner-controller/actions-runner-controller project on the Alibaba Cloud aks cluster to better serve our open source projects https://github.com/metaflowys/ metaflow.
Some functions of actions-runner-controller require generic-ephemeral-volumes requirements, but Alibaba Cloud cloud disk csi does not support it. I need a csi that can run in a serverless environment, so as to discard the garbage Ali that does not support this or that. cloud

**Comment by Nick-0314** [comment]
I may have some issues with serverless clusters not being able to run JFS, but this feature could be considered for support

**Comment by zwwhdls** [comment]
hi @mytting , refer to https://juicefs.com/docs/zh/csi/examples/generic-ephemeral-volume please. closing
