### ISSUE TITLE
[ENHANCE] add nightly integration test for shared mount

### ISSUE THREAD

**Issue by Hexilee** [juicedata/juicefs-csi-driver#421]
In #413, we fix a bug of shared mount without adding any integration test, because running an independent integration test in each pull request is too expensive.

However, to avoid this bug reoccur in the future, we need a nightly integration test to cover this case.

**Comment by zwwhdls** [comment]
Besides mount shared feature, also provisionser should be added in integration test.

**Comment by zwwhdls** [comment]
supported by https://github.com/juicedata/juicefs-csi-driver/pull/423
