### ISSUE TITLE
[FEATURE] juicefs support deployed on virtual kubelet

### ISSUE THREAD

**Issue by hustclf** [juicedata/juicefs-csi-driver#440]
**What feature you'd like to add:**
juicefs csi support deploy on virtual kubelet of public cloud(aliyun/tencentcloud/huaweicloud)

**Why is this feature needed:**
I have some elastic jobs deployed across multiple public cloud, and want to use juicefs for shared posix filesystem.

**Comment by davies** [comment]
JuiceFS depends on FUSE but most of the serverless platform do not allow FUSE in containers.

**Comment by hustclf** [comment]
Thanks.
