### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by ggaaooppeenngg** [juicedata/juicefs-csi-driver#444]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/juicedata/juicefs-csi-driver/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation: [JuiceFS CSI Driver Doc](https://juicefs.com/docs/csi/introduction/)

**What help did you want**:
juicefs mount with error "load setting: database is not formatted, please run `juicefs format ...`".
In the redis I got, it seems setting was lost if I did not miss it.  How to recover from the state? 
The csi-driver is keep working, I am afraid format will destroy the metadata. How to recovert from this state?
```
redis-cli -u redis://0.0.0.0:6379/7
0.0.0.0:6379[7]> scan 0
1) "0"
2) 1) "sessions"
   2) "totalInodes"
   3) "usedSpace"
0.0.0.0:6379[7]> get setting
(nil)
```
**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- v0.7.0
- Kubernetes version (e.g. `kubectl version`):
- 1.20.1
- Object storage (cloud provider and region):
- minio
- Metadata engine info (version, cloud provider managed or self maintained):
- redis
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- ok
- Others:
- When I tested it with juicefs 0.10.0 in the several months ago, the mout command worked. But now it fails.

**Comment by zwwhdls** [comment]
Hi @ggaaooppeenngg , can you describe the process how you test it with csi driver?

**Comment by ggaaooppeenngg** [comment]
@zwwhdls I created a PVC, mounted it, and write some files to check the persistence. It seems CSI driver can work without the setting metadata or it caches the setting so that it can work without loading the setting again until it restarts.

**Comment by zwwhdls** [comment]
Hi @ggaaooppeenngg , it seems redis has been flushed for some reason when juicefs mounted. 

You can recover it from metadata backups in object storage referring to this doc: 
https://juicefs.com/docs/community/metadata_dump_load/#automatic-backup
