### ISSUE TITLE
[QUESTION] Random pod termination with writeback mount option enable

### ISSUE THREAD

**Issue by lewandowskim1988** [juicedata/juicefs-csi-driver#451]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/juicedata/juicefs-csi-driver/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation: [JuiceFS CSI Driver Doc](https://juicefs.com/docs/csi/introduction/)

**What help did you want**:
I am running `juicefs-csi-driver` to manage storage for `nextflow` workloads.
With single run there is ~4TB of data that are transfer back and fourth S3 storage.
Everything is working super smooth for big files but when it comes to read/write of very large portion of small files it take ages to finish `nextflow` pipeline.
For comparison same pipeline with `AWS FSx` storage finish in ~2h and for `JuiceFS` was like ~9h. 
On monitoring I can also see huge spikes in `IO Latency` and `Objects Latency`.

To mitigate that I used `writeback` flag since it is mention in [doc](https://www.juicefs.com/docs/community/cache_management#client-write-data-cache) that it is meant to be used when there is a lot of operation on small files.
Along with adding this flag I change disk size to `500GB`, with `cache-size=384000`.

Unfortunately short after starting my pipeline I started to seeing lot of pods failing with following information:
```
"SyncLoop (PLEG): event for pod" pod="development/nf-0b9ef1795c888ad001b0ce06a2c4da9a" event=&{ID:953f3f19-ed54-4ad1-88db-740c046d6b46 Type:ContainerDied Data:2f5954273a6b0c48d742786771b98471312097dcf11e11f6f2b6ea20ad564d0b}
```
To give more information this pipeline is starting ~40 pods in peak and all are connected to same `JuiceFS` storage.
Are you able to give me some clue where I can search next to resolve my issue?

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): `v0.17.1`
- Kubernetes version (e.g. `kubectl version`): `1.21`
- Object storage (cloud provider and region): `S3` in `us-east-1`
- Metadata engine info (version, cloud provider managed or self maintained): `AWS ElastiCache Redis` version `6.2.6` in cluster mode with `cache.t4g.medium` instances 
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): `Redis` is in the same `VPC` and `region` as `k8s` cluster, `S3` bucket is linked with `VPC Endpoint`
- Others:

**Comment by zwwhdls** [comment]
Hi @lewandowskim1988 , can you provide the status and log of mount pod? You can refer to [this doc](https://juicefs.com/docs/csi/troubleshooting/#find-mount-pod)

**Comment by lewandowskim1988** [comment]
You can find logs from two `JuiceFS` pods.

[juicefs-ubimwo.txt](https://github.com/juicedata/juicefs-csi-driver/files/9936777/juicefs-ubimwo.txt)
[juicefs-utkhur.txt](https://github.com/juicedata/juicefs-csi-driver/files/9936778/juicefs-utkhur.txt)

**Comment by zwwhdls** [comment]
Hi @lewandowskim1988 ,  are these mount pods still running? Or failed?

**Comment by lewandowskim1988** [comment]
Those mount pods where terminated as soon as pod that was using `JuiceFS` storage was killed.
I have those logs from my log aggregation system.

**Comment by lewandowskim1988** [comment]
Hi @zwwhdls 
Any news regarding this problem?

**Comment by zwwhdls** [comment]
Hi @lewandowskim1988 , I suggest to increase resource requests and limits of mount pod, refer to [this doc](https://juicefs.com/docs/csi/guide/resource-optimization/#configure-resource-requests-and-limits-for-mount-pod). Also, you can set deleted delay of it, refer to [this doc](https://juicefs.com/docs/csi/guide/resource-optimization/#delayed-mount-pod-deletion).  Then reproduce this issue and see if mount pod is OOM.
