### ISSUE TITLE
[QUESTION] Storage quotas on nomad

### ISSUE THREAD

**Issue by c-vinet** [juicedata/juicefs-csi-driver#469]
Hello,
I am trying to setup CSI volumes for nomad, everything works fine, except i don't know how to set up storage quotas.
I tried setting the capacity parameter in different places, but i always see the default size of 1 Petabyte when i do a `df -h` in the container.
Is this supposed to work on Nomad?  Or maybe i am just doing it wrong...
Thanks for your help.

Here is my volume configuration: 
```
type = "csi"
id = "juicefs-volume"
name = "juicefs-volume"
capacity_max = "2G"
capacity_min = "2G"
#capacity=2
parameters {
  capacity=2
}
capability {
  access_mode = "multi-node-multi-writer"
  attachment_mode = "file-system"
}
plugin_id = "juicefs0"

secrets {
  name="juicefs-volume"
  #capacity=2
  metaurl="***"
  bucket="***"
  storage="minio"
  access-key="***"
  secret-key="***"
}
```

**Comment by zwwhdls** [comment]
`capacity` did not work so far.
