### ISSUE TITLE
[BUG] No such file or directory error when pod is mounted to pvc

### ISSUE THREAD

**Issue by iygq** [juicedata/juicefs-csi-driver#480]
No such file or directory error when pod is mounted to pvc
<img width="1475" alt="Pasted Graphic 14" src="https://user-images.githubusercontent.com/118091099/203737328-2461717a-95e2-40e4-a4dc-c4e7c6e6198f.png">

pv
<img width="1398" alt="Pasted Graphic 13" src="https://user-images.githubusercontent.com/118091099/203737416-f3d1ad70-6a8c-4992-a49d-041c3d1d3ac6.png">

csi-node
<img width="1293" alt="Pasted Graphic 12" src="https://user-images.githubusercontent.com/118091099/203737444-31176f8d-c33d-45e8-80b1-33efb006f39a.png">
<img width="1211" alt="Pasted Graphic 10" src="https://user-images.githubusercontent.com/118091099/203737483-b7a0e713-8d1b-46ea-ade7-95f5b6d35bdb.png">

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): v0.17.0
- Kubernetes version (e.g. `kubectl version`): v2.6.8
- Object storage (cloud provider and region): minio
- Metadata engine info (version, cloud provider managed or self maintained): redis
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): 
- Others:

**Comment by zwwhdls** [comment]
Hi @iygq ,

It seems several issues in your cluster:

1. Application pod can not be running , with error msg "no such file or directory"
    - Can you check if the CSI Node Service existed in node where application pod scheduled in ?
    - If CSI Node Service existed, can you check if its start time earlier or later than the event time "1.1mins ago"?
2. Cannot access file "0" in filesystm.
    - Can you provide application pod yaml here? 
    - Is your PVC "ReadOnlyMany"?

**Comment by zwwhdls** [comment]
Reopen if feedback. closing.
