### ISSUE TITLE
[FEATURE] graceful shutdown

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs-csi-driver#488]
**What feature you'd like to add:**

delete mount pod after app shutdown gracefully.

**Why is this feature needed:**

When the app pod is terminating, the app may be busy writing data into JuiceFS, we should not kill mount pod before app exit.

**Comment by zwwhdls** [comment]
This issue is caused by a bug. Pod driver in CSI Node regards pod that are marked deleted as removed, so it deleted mount pod upon the application pod is marked deleted when not actually removed.
