### ISSUE TITLE
[FEATURE] add option for disable the format phase

### ISSUE THREAD

**Issue by CodeRusher** [juicedata/juicefs-csi-driver#505]
**What feature you'd like to add:**
添加禁止format流程的选项
也即，format可以只作为环境准备的一部分，而不是csi的必要流程

**Why is this feature needed:**
例如，存储提供方（存储部门）和存储使用方（容器部门）属于不同的部门
存储提供方只提供已经预先做好format流程的 metaurl 即可，这样也不会暴露对象存储的秘钥等信息给使用方

**Comment by zwwhdls** [comment]
Hi @CodeRusher , only "metaurl" and "name" is required in secret. If you do `juicefs format` before and set "metaurl" and "name" in secret, mount pod will do `juicefs format <metaurl> <name> --no-update` without update s3 credentials. 

Did these meet your needs?

**Comment by CodeRusher** [comment]
thanks @zwwhdls , it works for me!!!

**Comment by wolgod** [comment]
> Hi @CodeRusher , only "metaurl" and "name" is required in secret. If you do `juicefs format` before and set "metaurl" and "name" in secret, mount pod will do `juicefs format <metaurl> <name> --no-update` without update s3 credentials.
> 
> Did these meet your needs?

I also have this problem. I am using ceph librados, but if I don’t provide storage and bucket, will the default values ​​be used? Why not provide a switch to turn it off?
