### ISSUE TITLE
provide registry credentials for JUICEFS_MOUNT_IMAGE

### ISSUE THREAD

**Issue by TheIronFlo** [juicedata/juicefs-csi-driver#521]
**What would you like to be added**:

I'd like to add registry credentials for my custom images as we use a private registry (Gitlab in our case).
Of course we can use a custom image as described in <https://juicefs.com/docs/csi/guide/custom-image/>:

```apiVersion: apps/v1
kind: DaemonSet
...
spec:
  template:
    spec:
      containers:
      - name: juicefs-plugin
        image: juicedata/juicefs-csi-driver:nightly
        env:
        - name: JUICEFS_MOUNT_IMAGE
          value: juicedata/mount:patch-some-bug
```

but only in public registries.

**Why is this needed**:

Because many registries are not public.

**Comment by TheIronFlo** [comment]
Additional: It might be enough to use the registry credentials from the DaemonSet. If none provided use none, if DaemonSet has registry credentials just re-use it.

**Comment by zwwhdls** [comment]
Hi @TheIronFlo , mount pod will inherit `ImagePullSecrets` from CSI Node DaemonSet.

**Comment by TheIronFlo** [comment]
> Hi @TheIronFlo , mount pod will inherit `ImagePullSecrets` from CSI Node DaemonSet.

Thx man, I didn't read this in the documentation. Looks like it works :-)

**Comment by zwwhdls** [comment]
Sorry @TheIronFlo , we will complete it in docs.
