### ISSUE TITLE
k8s部署juicefs,juicefs-pvc创建问题

### ISSUE THREAD

**Issue by liufangpeng** [juicedata/juicefs-csi-driver#548]
juicefs-10.79.188.50-pvc-88b0ba29-13a0-4c9e-bdc7-4a223402673e-lkosyk   0/1     Init:0/1   4 (4m47s ago)   19m

pod一直卡在init状态并且describe并无报错显示

Events:
  Type     Reason   Age                  From     Message
  ----     ------   ----                 ----     -------
  Warning  BackOff  116s (x3 over 6m8s)  kubelet  Back-off restarting failed container
  Normal   Pulled   103s (x4 over 13m)   kubelet  Container image "juicedata/mount:v1.0.3-4.8.3" already present on machine
  Normal   Created  103s (x4 over 13m)   kubelet  Created container jfs-format
  Normal   Started  103s (x4 over 13m)   kubelet  Started container jfs-format

**Comment by zwwhdls** [comment]
Hi @liufangpeng , can you provide the log of jfs-format container in mount pod?

```
kubectl -n kube-system logs juicefs-10.79.188.50-pvc-88b0ba29-13a0-4c9e-bdc7-4a223402673e-lkosyk -c jfs-format
```

**Comment by liufangpeng** [comment]
2023/01/12 06:52:19.196508 juicefs[7] <INFO>: Meta address: redis://:****@10.79.188.49:16379/6 [interface.go:402]

**Comment by zwwhdls** [comment]
Can you add `--debug` and execute the command of initContainer manually inside juicefs csi node?

```
juicefs format xxx xxxx --debug
```

**Comment by liufangpeng** [comment]
xxx xxxx 代表[redis](redis://:****@10.79.188.49:16379/6)这个吗

**Comment by liufangpeng** [comment]
redis://:****@10.79.188.49:16379/6

**Comment by zwwhdls** [comment]
就是在 jfs-format 这个容器的 command 后面加个 --debug，然后在 csi node pod 里执行一遍
