### ISSUE TITLE
Juicefs-CSI 咨询

### ISSUE THREAD

**Issue by liufangpeng** [juicedata/juicefs-csi-driver#550]
在K8S上面部署了，并且成功挂载了OBS，但是我想把容器内挂载过的目录里的文件同步到对象存储这个应该怎么操作呢

**Comment by liufangpeng** [comment]
还有个问题，我挂载的桶里出现了好多名为
dump-2023-01-31-163144.json.gz 的文件，juicefs-csi是自带什么备份机制吗

**Comment by zwwhdls** [comment]
1. 找到 [应用 对应的 mount pod](https://juicefs.com/docs/zh/csi/troubleshooting#csi-doctor) 后，exec 进去执行 [juicefs sync](https://juicefs.com/docs/zh/community/command_reference#juicefs-sync) 即可同步。
2. 是 juicefs 自 1.0.0 后开启的元数据自动备份功能，参考[文档](https://juicefs.com/docs/zh/community/metadata_dump_load#%E8%87%AA%E5%8A%A8%E5%A4%87%E4%BB%BD)

**Comment by liufangpeng** [comment]
用K8s部署的juicefs-CSI，如果要自定义备份时间这个需要在哪里修改呢

**Comment by liufangpeng** [comment]
我在一个挂载了obs的pvc的pod里看到
JuiceFS:test              1.0P     20.0K   1024.0T   0% /config
这个挂载成功的成果，但是这个pod里没有juicefs的命令我如何做到同步呢

**Comment by zwwhdls** [comment]
1. 自定义备份时间在[挂载参数 option ](https://juicefs.com/docs/zh/community/command_reference#mount)里指定，挂载参数配置参考文档：https://juicefs.com/docs/zh/csi/guide/pv#mount-options
2. juicefs sync 命令在 mount pod（运行 juicefs 客户端的 pod） 中执行，通过应用 pod 找 mount pod 参考文档：https://juicefs.com/docs/zh/csi/troubleshooting#csi-doctor 或 https://juicefs.com/docs/zh/csi/troubleshooting#check-mount-pod

**Comment by timfeirg** [comment]
mount pod 的容器镜像中包含 juicefs 客户端, 这点我们补充进了文档: https://github.com/juicedata/juicefs-csi-driver/pull/553/files#diff-4ae060c6bc8ae73b48b7f33108c356a1147e077efc1200e659f0bf5d94eee515R179
