### ISSUE TITLE
[BUG] juicefs controller can't read metadata/files on S3 bucket after reboot

### ISSUE THREAD

**Issue by metronlab-it** [juicedata/juicefs-csi-driver#551]
**What happened**:
If you set up a nomad volume using juicefs and an S3 bucket as the storage, any reboot of the controller will give an error the next time the volume is used:

>  <FATAL>: Storage s3://[bucket] is not empty; please clean it up or pick another volume name [format.go:443]

The only way to recover is to delete the nomad volume, delete the contents of the s3 bucket, and recreate it. This means that juicefs over S3 is effectively useless as a storage solution for a production system, as at some stage restarts are inevitable. 

**What you expected to happen**:

A simple reboot of the controller job should be able to read the files/metadata created by the previous job.

**How to reproduce it (as minimally and precisely as possible)**:
- create a nomad volume with an S3 bucket as the object storage and redis as the metadata engine

```
type = "csi"
id = "staging-europe-paris-emm-s3-sftpgo"
name = "staging-europe-paris-emm-s3-sftpgo"

capability {
access_mode = "multi-node-multi-writer"
attachment_mode = "file-system"
}
plugin_id = "juicefs0"

secrets {
  name="staging-europe-paris-emm-s3-sftpgo"
  metaurl="redis://redis-local/0"
  bucket="https://staging-europe-paris-emm-s3-sftpgo.s3.eu-west-3.amazonaws.com"
  storage="s3"
  access-key="xxxxx"
  secret-key="xxxxx"
}
```
- mount the volume on an application (I'm using sftpgo)
- restart the juicefs controller job
- the application won't be able to read its volume any more

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): v0.17.5
- Object storage (cloud provider and region): AWS S3 bucket, eu-west-3
- Metadata engine info (version, cloud provider managed or self maintained): redis version 7.0.4 
- Network connectivity: JuiceFS to object storage
- Others: terraform v1.1.6 to create the nomad jobs/volumes. NOT using kubernetes for anything.

**Comment by zwwhdls** [comment]
Hi @metronlab-it , juicefs csi only support [`process mount mode`](https://juicefs.com/docs/csi/introduction/#by-process) in nomad. Juicefs mount processes run in juicefs controller job all. So, when juicefs controller restart, mount processes are all killed.

After juicefs controller restart, all application jobs which use juicefs volumes should restart also. closing.
