### ISSUE TITLE
[FEATURE] one juicefs client to rule them all

### ISSUE THREAD

**Issue by timfeirg** [juicedata/juicefs-csi-driver#566]
currently both juicefs ce / ee client binary resides in mount pod image, as described in the docs:

> If you need to run JuiceFS Client inside mount pod, note that JuiceFS Community Edition and JuiceFS Cloud Service Clients are both included in the container image, and you need to select a specific client through an absolute path:

> /usr/local/bin/juicefs: JuiceFS Community Edition client
> /usr/bin/juicefs: JuiceFS Cloud Service client

maybe we can detect the actual edition being used (during mount pod start), and leave only one juicefs client inside the container, so that users don't mistake one for another.

**Comment by zwwhdls** [comment]
Community and enterprise image has been split. Two binaries will no longer interfere with each other. Closing.
