### ISSUE TITLE
[QUESTION] CSI Driver with kerberized hdfs

### ISSUE THREAD

**Issue by kyungwan-nam** [juicedata/juicefs-csi-driver#572]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/juicedata/juicefs-csi-driver/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation: [JuiceFS CSI Driver Doc](https://juicefs.com/docs/csi/introduction/)

**What help did you want**:

I'm trying to JuiceFS CSI Driver with kerberized hdfs.
in my understanding, It requires ``kinit`` first, then JuiceFS authenticate using ``KRB5CCNAME``.
but, I couldn't figure out how to do that under CSI Driver.
Could you help me? Thanks.

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): juicedata/juicefs-csi-driver:v0.18.0
- Kubernetes version (e.g. `kubectl version`): v1.19.9
- Object storage (cloud provider and region): hdfs
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by tangyoupeng** [comment]
Did you mean use HDFS as storage backend? You can try kinit in local machine and add generated ccache file to pod.
https://juicefs.com/docs/csi/guide/pv/#mount-pod-extra-files

**Comment by kyungwan-nam** [comment]
@tangyoupeng 
Thanks to your advice I did it! Thank you for letting me know

I have another question.
generated ccache file would be expired at the end.
so, I have to update ccache secret whenever accessing juicefs.
Isn't there any way to authenticate using my keytab file instead of ccache file?

**Comment by tangyoupeng** [comment]
Maybe you could try run `kinit` periodically to update ccache

**Comment by zwwhdls** [comment]
closed by https://github.com/juicedata/juicefs/pull/3517
