### ISSUE TITLE
[BUG] PVC mounts never update

### ISSUE THREAD

**Issue by jgillich** [juicedata/juicefs-csi-driver#574]
**What happened**:

I changed the `metaurl` from `6379` to the Redis sentinel port `26379` (via Helm). This updated the `juicefs-secret`, but not any existing pvc mounts nor their secrets. They continue to use the old port, and I don't see a way to update them.

**What you expected to happen**:

When the storage class configuration changes, existing mounts should be updated.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install csi-driver helm chart
2. Create a PVC
3. Update the configuration of your storage class via helm values
4. Check that the changes were applied to the storage class secret
5. Check the PVC and see that it did not update

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): v0.18.0
- Kubernetes version (e.g. `kubectl version`): minikube / 1.23
- Object storage (cloud provider and region): minio
- Metadata engine info (version, cloud provider managed or self maintained): Redis sentinel cluster
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): K8s local
- Others:

**Comment by jgillich** [comment]
It does at least create new mounts when the mount is failing due to bad configuration, but the old mounts are never cleaned up. And when you delete the pods by hand, they'll get recreated.

![Screenshot from 2023-02-19 17-42-04](https://user-images.githubusercontent.com/347965/219961950-28cd022e-671c-4c57-a405-0eed0a9ef03f.png)

**Comment by zwwhdls** [comment]
Hi @jgillich , it only works with new mounts or old mounts restart to get newest configurations. This is as expected. 

Old mounts can not get newest configurations without restart because kubelet only transfer newest configurations when creating pod.

**Comment by jgillich** [comment]
I see, thanks! Took me a while to figure out that I have to recreate the mounting pod to update the juicefs pods.

**Comment by jgillich** [comment]
Seems like updating the storage class isn't allowed by K8s anyway: `updates to parameters are forbidden`

Is removing and reinstalling the CSI chart a safe operation? It doesn't affect existing PVCs, right? This is a dev env, but I wonder how I could make changes in production if necessary.

**Comment by zwwhdls** [comment]
@jgillich , You doesn't have to update storageClass nor reinstall CSI chart. In this issue, updating `metaurl` in secret and restarting application pod which uses juicefs PVC is ok.
