### ISSUE TITLE
[BUG] JUICEFS_MOUNT_IMAGE does not take effect for Job/delvol

### ISSUE THREAD

**Issue by fungaren** [juicedata/juicefs-csi-driver#587]
**What happened**:

As documented, the environment `JUICEFS_MOUNT_IMAGE` can use a different image for MountPods, this is OK:

```text
# kubectl get -n kube-system ds/juicefs-csi-node -ojsonpath='{.spec.template.spec.containers[0].env[?(@.name=="JUICEFS_MOUNT_IMAGE")].value}'
example.com/repo/test:1.0.0
```

Relavent code: 

https://github.com/juicedata/juicefs-csi-driver/blob/14793999fbabbfecb2722524b7312553b2796bba/cmd/controller.go#L69

However, when deleting the Workload and PVC, the created Job (to delete the relevant PV) will not use the image as specified in `JUICEFS_MOUNT_IMAGE`.

```text
# kubectl get job/juicefs-5052b2e4-delvol -n kube-system -ojsonpath='{.spec.template.spec.containers[0].image}'
juicedata/mount:v1.0.3-4.8.3
```

It is also unable to solve this problem by setting `juicefs/mount-image` parameter in StorageClass. Relevant code:

https://github.com/juicedata/juicefs-csi-driver/blob/14793999fbabbfecb2722524b7312553b2796bba/pkg/config/setting.go#L246

After looking around, maybe the reason is in `DeleteVolume()`, `VolCtx` is not passed to `JfsDeleteVol`:

https://github.com/juicedata/juicefs-csi-driver/blob/14793999fbabbfecb2722524b7312553b2796bba/pkg/driver/controller.go#L122

**What you expected to happen**:

The job for delete volumes will also use that image.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zwwhdls** [comment]
Hi @fungaren , can you check if set `JUICEFS_MOUNT_IMAGE ` in CSI Controller too? The vol-del job is created by CSI Controller instead of CSI Node.

**Comment by fungaren** [comment]
@zwwhdls I didn't set `JUICEFS_MOUNT_IMAGE` for juicefs-csi-controller, because your document didn't say that. 

https://juicefs.com/docs/zh/csi/guide/custom-image

**Comment by zwwhdls** [comment]
@fungaren Sorry, that's a mistake in doc, we'll fix it asap. Can you also set it in juicefs-csi-controller? 

```
kubectl -n kube-system set env statefulset/juicefs-csi-controller -c juicefs-plugin JUICEFS_MOUNT_IMAGE=juicedata/mount:v1.0.3-4.8.3
```

**Comment by fungaren** [comment]
@zwwhdls  Yes, after set the environment, it works now.

```text
# kubectl get -n kube-system sts/juicefs-csi-controller -ojsonpath='{.spec.template.spec.containers[0].env[?(@.name=="JUICEFS_MOUNT_IMAGE")].value}'
example.com/repo/test:1.0.0
# kubectl get job/juicefs-12c5fdce-delvol -n kube-system -ojsonpath='{.spec.template.spec.containers[0].image}'
example.com/repo/test:1.0.0
```

But by setting `juicefs/mount-image` still has no effect (of course meanwhile `JUICEFS_MOUNT_IMAGE` is not set), maybe it is a bug?

And based on the same reason, the `delvol` pod will not be `hostNetwork: true` even if `juicefs-csi-node` is `hostNetwork: true`.

**Comment by zwwhdls** [comment]
@fungaren , yes, kind of bug. Thanks for raising it out.

**Comment by fungaren** [comment]
I also tried making the `juicefs-csi-controller` to be `hostNetwork: true` by this:

```bash
kubectl -n kube-system patch ds/juicefs-csi-node --type json --patch \
'[{"op": "add", "path": "/spec/template/spec/hostNetwork", "value": true}]'
kubectl patch -nkube-system sts/juicefs-csi-controller --type json --patch \
'[{"op": "replace", "path": "/spec/template/spec/containers/0/ports/0", "value": {"hostPort": 9910, "containerPort": 9910, "name": "healthz", "protocol": "TCP"}}, '\
'{"op": "add", "path": "/spec/template/spec/hostNetwork", "value": true}, '\
'{"op": "replace", "path": "/spec/template/spec/containers/2/env/1/value", "value": "9910"}]'
```

Now both CSI controller & CSI node are hostNetwork, but the Job is not:

```text
# kubectl get ds/juicefs-csi-node -n kube-system -ojsonpath='{.spec.template.spec.hostNetwork}'
true
# kubectl get sts/juicefs-csi-controller -n kube-system -ojsonpath='{.spec.template.spec.hostNetwork}'
true
# kubectl get job/juicefs-c85d499f-delvol -n kube-system -ojsonpath='{.spec.template.spec.hostNetwork}'
```

Pretty weird.

**Comment by zwwhdls** [comment]
That's because hostNetwork is got from CSI Node pod but Controller pod do not has it. It's better to got it from CSI Node daemonset instead of pod.

**Comment by fungaren** [comment]
@zwwhdls Yes, as you said that the the vol-del job is created by CSI Controller, and it seems that `config.CSIPod` object will not be set in CSI Controller, instead, it will only be set in CSI Node right? That's why the created Job is not hostNetwork. 🤣 Will you fix this?

**Comment by zwwhdls** [comment]
sure
