### ISSUE TITLE
[FEATURE] support hostPath for mount pod

### ISSUE THREAD

**Issue by CodeRusher** [juicedata/juicefs-csi-driver#592]
**What feature you'd like to add:**
MountPod支持自定义hostPath

**Why is this feature needed:**
场景一：将juicefs的日志映射到宿主机上，方便宿主机上日志收集工具收集

**Comment by zwwhdls** [comment]
Hi @CodeRusher , juicefs client runs foreground in mount pod. So, mount pod's log is juicefs log. You can collect mount pod log refer to https://juicefs.com/docs/zh/csi/administration/going-production#%E5%9C%A8-efk-%E4%B8%AD%E6%94%B6%E9%9B%86-mount-pod-%E6%97%A5%E5%BF%97

**Comment by zwwhdls** [comment]
closed by https://github.com/juicedata/juicefs-csi-driver/pull/703
