### ISSUE TITLE
是否支持跨namespace共享pvc

### ISSUE THREAD

**Issue by weiwuduzui** [juicedata/juicefs-csi-driver#596]
请问要在两个namespace中存储相同的内容，是否支持跨namespace共享同一个pvc的情况

**Comment by fungaren** [comment]
pvc 是 namespaced-scope 资源，你用静态 pv 吧。然后在多个 pvc 里面引用相同 pv

**Comment by zwwhdls** [comment]
Hi @fungaren , PVC is namespaced-scope as @fungaren metioned. And PVC is bound to PV one by one referring to  https://kubernetes.io/docs/concepts/storage/persistent-volumes/#binding . 

You can set the same secret in different PVs, create different PVCs to each PV. Then pod using PVC, so they can access the same file system.

**Comment by zwwhdls** [comment]
docs updated in https://github.com/juicedata/juicefs-csi-driver/pull/599
