### ISSUE TITLE
Install juicefs-csi-driver throw kind "CSIDriver" in version "storage.k8s.io/v1" on k8s 1.15

### ISSUE THREAD

**Issue by wph95** [juicedata/juicefs-csi-driver#60]
as the document said, CSI-driver support k8s version v1.13+
btw in k8s 1.14/1.15 CSI feature is Beta
so need an install file which 

```
apiVersion: storage.k8s.io/v1beta1
# apiVersion: storage.k8s.io/v1 

kind: CSIDriver
```

**Comment by chnliyong** [comment]
>  so need an install file which

Yeah, you are right. We'll do more Kubernetes version test. Thanks!

**Comment by davies** [comment]
So this should be fixed, thanks!
