### ISSUE TITLE
Autoacaling the controller statefulset

### ISSUE THREAD

**Issue by hyphen1370** [juicedata/juicefs-csi-driver#638]
Hello,

After deploying the csi driver, I see there is statefulset created as controller. How could I apply autoscaling to statefulset? Is the HPA with checking cpu and memory going to work? Or does it require additional work?

Thanks

**Comment by zwwhdls** [comment]
Hi @hyphen1370 , sorry for late reply. HPA with checking cpu and memory is ok and no more work is needed. Thanks.
