### ISSUE TITLE
Sock error with Nomad, since upgrade of juicedata/juicefs-csi-driver:v0.18.0

### ISSUE THREAD

**Issue by AlbanAndrieu** [juicedata/juicefs-csi-driver#639]
**What happened**:

Sock error with Nomad, since upgrade of juicedata/juicefs-csi-driver:v0.18.0

```
Error: CSI plugin failed probe: timeout while connecting to gRPC socket: failed to stat socket: stat /var/nomad/client/csi/plugins/082c4b7d-758f-6e59-5299-0ed23b872345/csi.sock: no such file or directory
```

**What you expected to happen**:
It was working with juicedata/juicefs-csi-driver:v0.17.4

**How to reproduce it (as minimally and precisely as possible)**:
Switch from juicedata/juicefs-csi-driver:v0.17.4 to juicedata/juicefs-csi-driver:v0.18.0

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: v0.18.0
- Cloud provider or hardware configuration running JuiceFS: Nomad 
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained): S3 Bucket on OVH
- Metadata engine info (version, cloud provider managed or self maintained): Redis
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zwwhdls** [comment]
Hi @AlbanAndrieu , can you add env "POD_NAME" in controller and node service ? Referring to the doc: https://juicefs.com/docs/zh/csi/csi-in-nomad and issue: https://github.com/juicedata/juicefs-csi-driver/issues/619

**Comment by AlbanAndrieu** [comment]
Indeed adding POD_NAME fixed it. Add it to your example doc maybe for the others...

**Comment by azoller1** [comment]
Sorry, but Just wanted to comment, according to these docs https://juicefs.com/docs/csi/csi-in-nomad, the `env` variable is not capitalized but needs to be `POD_NAME` or else same error appears (didn't work for me until env name was all caps, I think that is how nomad works?). Anyways, thanks for at least providing nomad support :+1: 

Just for the controller example.

**Comment by zwwhdls** [comment]
@azoller1 , so sorry for the mistake in doc. It should be POD_NAME. We will fix it asap.
