### ISSUE TITLE
[BUG][WSL2] failed to generate spec: path "/var/lib/juicefs/volume" is mounted on "/" but it is not a shared mount

### ISSUE THREAD

**Issue by jmu** [juicedata/juicefs-csi-driver#647]
**What happened**:
I successfully installed the driver using Helm in the k3s cluster, and all the juicefs-csi-node nodes are working well, except for the node running on WSL2. The pod of juicefs-csi-node fails to start and reports the following error:

May  5 09:48:14 hole k3s[358]: E0505 09:48:14.842483     358 remote_runtime.go:442] "CreateContainer in sandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to generate container \"734387b16e7e418bfe1f5a9b1c3b4ce4f801dc2f2d5e7ca22f3b5b742b72f95a\" spec: failed to generate spec: path \"/var/lib/juicefs/volume\" is mounted on \"/\" but it is not a shared mount" podSandboxID="0a8df53ad930e3754b56f5cd05a27cf1f37338d100d6269bd1d726f41bc0c015"
May  5 09:48:14 hole k3s[358]: E0505 09:48:14.842661     358 kuberuntime_manager.go:862] container &Container{Name:juicefs-plugin,Image:juicedata/juicefs-csi-driver:v0.19.0,Command:[],Args:[--endpoint=$(CSI_ENDPOINT) --logtostderr --nodeid=$(NODE_NAME) --v=5 --enable-manager=true],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:healthz,HostPort:0,ContainerPort:9909,Protocol:TCP,HostIP:,},},Env:[]EnvVar{EnvVar{Name:CSI_ENDPOINT,Value:unix:/csi/csi.sock,ValueFrom:nil,},EnvVar{Name:NODE_NAME,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:spec.nodeName,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:POD_NAME,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.name,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:JUICEFS_MOUNT_NAMESPACE,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:HOST_IP,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:status.hostIP,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:KUBELET_PORT,Value:10250,ValueFrom:nil,},EnvVar{Name:JUICEFS_MOUNT_PATH,Value:/var/lib/juicefs/volume,ValueFrom:nil,},EnvVar{Name:JUICEFS_CONFIG_PATH,Value:/var/lib/juicefs/config,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{cpu: {{1 0} {<nil>} 1 DecimalSI},memory: {{1073741824 0} {<nil>} 1Gi BinarySI},},Requests:ResourceList{cpu: {{100 -3} {<nil>} 100m DecimalSI},memory: {{536870912 0} {<nil>}  BinarySI},},},VolumeMounts:[]VolumeMount{VolumeMount{Name:kubelet-dir,ReadOnly:false,MountPath:/var/lib/kubelet,SubPath:,MountPropagation:*Bidirectional,SubPathExpr:,},VolumeMount{Name:plugin-dir,ReadOnly:false,MountPath:/csi,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:device-dir,ReadOnly:false,MountPath:/dev,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:jfs-dir,ReadOnly:false,MountPath:/jfs,SubPath:,MountPropagation:*Bidirectional,SubPathExpr:,},VolumeMount{Name:jfs-root-dir,ReadOnly:false,MountPath:/root/.juicefs,SubPath:,MountPropagation:*Bidirectional,SubPathExpr:,},VolumeMount{Name:kube-api-access-762vm,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:&Probe{ProbeHandler:ProbeHandler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/healthz,Port:{1 0 healthz},Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,GRPC:nil,},InitialDelaySeconds:10,TimeoutSeconds:3,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:5,TerminationGracePeriodSeconds:nil,},ReadinessProbe:nil,Lifecycle:&Lifecycle{PostStart:nil,PreStop:&LifecycleHandler{Exec:&ExecAction{Command:[/bin/sh -c rm /csi/csi.sock],},HTTPGet:nil,TCPSocket:nil,},},TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,},Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} start failed in pod juicefs-csi-node-s9g9q_kube-system(b98ad75c-d926-4169-b5c6-28f19d6612d9): CreateContainerError: failed to generate container "734387b16e7e418bfe1f5a9b1c3b4ce4f801dc2f2d5e7ca22f3b5b742b72f95a" spec: failed to generate spec: path "/var/lib/juicefs/volume" is mounted on "/" but it is not a shared mount

May  5 09:34:49 hole k3s[358]: E0505 09:34:49.835165     358 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"juicefs-plugin\" with CreateContainerError: \"failed to generate container \\\"cf882311fb406a6f41c6321b5f6ea32ab58736b2f871b5d9964eae2079e7c215\\\" spec: failed to generate spec: path \\\"/var/lib/juicefs/volume\\\" is mounted on \\\"/\\\" but it is not a shared mount\"" pod="kube-system/juicefs-csi-node-s9g9q" podUID=b98ad75c-d926-4169-b5c6-28f19d6612d9

**What you expected to happen**:
normal starts as orther nodes

**How to reproduce it (as minimally and precisely as possible)**:
add a WSL2   as  k3s node， and install juicefs-csi-driver

**Anything else we need to know?**
default mountpod mode

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
0.19

- Kubernetes version (e.g. `kubectl version`):
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.7+k3s1", GitCommit:"f7c20e237d0ad0eae83c1ce60d490da70dbddc0e", GitTreeState:"clean", BuildDate:"2023-03-10T22:01:42Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.7+k3s1", GitCommit:"f7c20e237d0ad0eae83c1ce60d490da70dbddc0e", GitTreeState:"clean", BuildDate:"2023-03-10T22:01:42Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/arm64"}
- Object storage (cloud provider and region):
nothing to do with this
- Metadata engine info (version, cloud provider managed or self maintained):
self maintained
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:
- wsl --version
WSL 版本： 1.1.3.0
内核版本： 5.15.90.1
WSLg 版本： 1.0.49
MSRDC 版本： 1.2.3770
Direct3D 版本： 1.608.2-61064218
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22621.1555

*node OS info：*
Linux hole 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zwwhdls** [comment]
It seems the same issue as https://github.com/kubernetes-csi/csi-driver-smb/issues/335#issuecomment-896759440. Can you add /bin/mount --make-shared /var/lib/juicefs in your agent node config and have a retry?

**Comment by devenami** [comment]
hi, i have same problem, now i solve this problem by [Node plugin pod does not start with RunContainerError status](https://kubernetes-csi.github.io/docs/troubleshooting.html#node-plugin-pod-does-not-start-with-runcontainererror-status)

if you use docker, just update docker service

```
# old
MountFlags=slave
``` 

to

```
# new
MountFlags=shared
```

then reload docker use `systemctl daemon-reload && systemctl restart docker`.

**Warning**

if you update docker service and restart docker, the node's all pods will restart.

**Comment by jmu** [comment]
> hi, i have same problem, now i solve this problem by [Node plugin pod does not start with RunContainerError status](https://kubernetes-csi.github.io/docs/troubleshooting.html#node-plugin-pod-does-not-start-with-runcontainererror-status)
> 
> if you use docker, just update docker service
> 
> ```
> # old
> MountFlags=slave
> ```
> 
> to
> 
> ```
> # new
> MountFlags=shared
> ```
> 
> then reload docker use `systemctl daemon-reload && systemctl restart docker`.
> 
> **Warning**
> 
> if you update docker service and restart docker, the node's all pods will restart.

I use k3s, it seems like use containerd instead of Docker..

**Comment by jmu** [comment]
> It seems the same issue as [kubernetes-csi/csi-driver-smb#335 (comment)](https://github.com/kubernetes-csi/csi-driver-smb/issues/335#issuecomment-896759440). Can you add /bin/mount --make-shared /var/lib/juicefs in your agent node config and have a retry?

I fix by running this cmd `sudo mount --make-rshared /` , thanks a lot.
