### ISSUE TITLE
I created a volume webhook

### ISSUE THREAD

**Issue by breuerfelix** [juicedata/juicefs-csi-driver#652]
Hey,

since juicefs volumes need the config HostToContainer in order to recover from pod restarts, i created a webhook that adds this annotation to all volumes which have a certain storage class for example.

https://github.com/breuerfelix/juicefs-volume-hook

Since this could be useable for some other people i thought you might want to add this to the documentation. If not, thats also fine, just wanted to mention it at least somewhere

Cheers

**Comment by zwwhdls** [comment]
Hi @breuerfelix , thanks a lot for your contributions!
