### ISSUE TITLE
[QUESTION]how to understand some processes of  function podDeletedHandler  in pod_driver.go

### ISSUE THREAD

**Issue by Qipccc** [juicedata/juicefs-csi-driver#656]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/juicedata/juicefs-csi-driver/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation: [JuiceFS CSI Driver Doc](https://juicefs.com/docs/csi/introduction/)

**What help did you want**:
Hi~ I'm learning juicefs-csi-drice source code, and I have few code questions as blows:
1. First question is , in fuction `podDeletedHandler `,  it remove finalizer of pod firstly and then umount source path, so if pod corrupt after remove finalizer and  before umount source path,  is the source path may be left over?
2.   Second, in https://github.com/juicedata/juicefs-csi-driver/blob/master/pkg/controller/pod_driver.go#L357, is that mean if source path is NOT exist, it would umount source path instead of if source path exists  it would be umount? it seems strange, how should i understand it?

Hope to get your reply，thanks.

**Comment by Hexilee** [comment]
Hi! Thanks for your interest, I'm trying to answer your two questions:
1. We have already cleaned up the mount point in the [PreStop](https://github.com/juicedata/juicefs-csi-driver/blob/master/pkg/juicefs/mount/builder/pod.go#LL62C10-L62C10) of mount container, the following cleanup after removing finalizer is a double check.
2. This is a bug, it should be `err == nil`, we are planning to fix it, thank you very much.

**Comment by Qipccc** [comment]
Thanks for your reply.
Please excuse me for asking another question. I'm also confused about the [PreStop](https://github.com/juicedata/juicefs-csi-driver/blob/master/pkg/juicefs/mount/builder/pod.go#LL62C67-L62C67) hook in which rmdir is used to remove `r.jfsSetting.MountPath`, and from the code, I can only see that this path is created when [CreateVol](https://github.com/juicedata/juicefs-csi-driver/blob/master/pkg/juicefs/juicefs.go#LL187C19-L187C19) is called. So, if `r.jfsSetting.MountPath` is removed, when will it be recreated? As far as I understand, when the mounted Pod restarts, it will call podReadyHandler, but I haven't seen any operation like mkdir or anything similar.
