### ISSUE TITLE
support store juicefs log in juicefs-csi-node

### ISSUE THREAD

**Issue by chnliyong** [juicedata/juicefs-csi-driver#66]
Currently _JuiceFS_ mount process's log is lost, we need to capture it to a log file for troubleshooting.

**Comment by swartz-k** [comment]
I think may add it at `kflog.InitFlags` [cmd/main.go#L34](https://github.com/juicedata/juicefs-csi-driver/blob/d085085ad0ea9930155f4a752e3cfda0c160394a/cmd/main.go#L34)

**Comment by davies** [comment]
Fixed by #68
