### ISSUE TITLE
[QUESTION] Anybody tries to use sqlite to be metaengine? always show sqlite.db is unavailable

### ISSUE THREAD

**Issue by KiwiGeorge** [juicedata/juicefs-csi-driver#671]

**Comment by zwwhdls** [comment]
Hi @KiwiGeorge , sqlite is not recommended to be meta engine in csi. Because juicefs client is running in a single pod and can not reach sqlite otherwhere.

**Comment by KiwiGeorge** [comment]
> Hi @KiwiGeorge , sqlite is not recommended to be meta engine in csi. Because juicefs client is running in a single pod and can not reach sqlite otherwhere.

Thank you for your reply, I tried many methods, such as setting up another pv and pvc using hostPath and I found that CSI vol and HostPath vol cannot mount on the same path, so.... You mean CSI Meta engine can only use online database?

**Comment by zwwhdls** [comment]
@KiwiGeorge  sqlite should be mounted in mount pod (juicefs client runs in) and make juicefs client reach it. But hostPath for mount pod is not supported yet. You can easily replace sqlite with redis.

**Comment by KiwiGeorge** [comment]
You mean we cannot mkdir a path in pod for sqlite to mount before we mount juicefs on the mount path? I mean we can do like this screen shot shows to ensure juicefs having the access for sqlite
<img width="417" alt="截屏2023-06-25 10 05 31" src="https://github.com/juicedata/juicefs-csi-driver/assets/118660995/0c9b6401-b26b-4deb-924f-6da4f0ce6447">
