### ISSUE TITLE
[QUESTION] What's the protocol used between JuiceFS and Pod/Volume? In other words, how to achieve mount between pod path and Juicefs.path? 

### ISSUE THREAD

**Issue by KiwiGeorge** [juicedata/juicefs-csi-driver#672]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/juicedata/juicefs-csi-driver/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation: [JuiceFS CSI Driver Doc](https://juicefs.com/docs/csi/introduction/)

**What help did you want**:

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zwwhdls** [comment]
Hi @KiwiGeorge , you can read [docs of JuiceFS CSI Driver architecture](https://juicefs.com/docs/csi/introduction/#architecture) for more details. Thanks.
