### ISSUE TITLE
[QUESTION] Failed on setting PV storage capacity

### ISSUE THREAD

**Issue by kirakiseki** [juicedata/juicefs-csi-driver#674]
## Question

**What help did you want**:
I'm using KubeSphere and setuped JuiceFS CSI Driver following this [Doc](https://juicefs.com/docs/community/juicefs_on_kubesphere/). 
Everything goes well during installation, and I created a StorageClass manually. 

StorageClass configuration as follow:
<img width="898" alt="image" src="https://github.com/juicedata/juicefs-csi-driver/assets/38367158/abf45101-99b0-4c38-92b3-986d4b547f3f">

PVC Configuration:
<img width="383" alt="image" src="https://github.com/juicedata/juicefs-csi-driver/assets/38367158/a70e4df7-182b-4f8e-b943-97523a90305b">
**I have limited 10Gi storage capacity here.**

And I tried to use this PVC in a Centos Deployment. I used KubeSphere GUi to bind the pvc to this container. 
Part of Deployment Configuration:
<img width="666" alt="image" src="https://github.com/juicedata/juicefs-csi-driver/assets/38367158/4e072161-c286-4d95-a1a6-777346cc63ea">

But questions occured here:
![image](https://github.com/juicedata/juicefs-csi-driver/assets/38367158/0888f506-edc1-4bb6-a6db-547ab980dbf8)
In command `df -sh`, it returns size as 1.0P other than 10Gi, and I can still write 20Gi to a 10Gi PVC.

As doc [Create and Use PV](https://juicefs.com/docs/csi/guide/pv/) said, I'm using "Dynamic provisioning" and it's able to limit the storage capacity in it. But I can still write file whose size is larger than the capacity i have ever set. 

And I also tried the `config.yaml` given in [#dynamic-provisioning](https://juicefs.com/docs/csi/guide/pv/#dynamic-provisioning), and the result as above too.
![image](https://github.com/juicedata/juicefs-csi-driver/assets/38367158/e1ac6032-ad73-4f2b-9eb1-fc33a4ee32aa)
<img width="1162" alt="image" src="https://github.com/juicedata/juicefs-csi-driver/assets/38367158/e25606db-1d82-4067-9879-d79d06afccaa">

So what's wrong with my configuration or I'm facing some feature/bugs? And how can I fix it to set capacity for each PV? Thanks for your generous help.

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): v0.18.0
- Kubernetes version (e.g. `kubectl version`): v1.23.10
- Object storage (cloud provider and region): Minio on OpenELB Hostpath volume
- Metadata engine info (version, cloud provider managed or self maintained): Redis v7.0.11
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): Redis on host, JuiceFS CSI Driver installed on Kubesphere
- Others: None

**Comment by zwwhdls** [comment]
Hi @kirakiseki , juicefs csi driver supports PVC capacity since v0.20.0 (juicefs v1.1.0-beta1). We has raise a [PR](https://github.com/kubesphere/helm-charts/pull/308) to release juicefs csi driver v0.20.0 (juicefs v1.1.0-beta1). 

After Kubesphere app store upgraded, please have a retry. Closing, thanks.
