### ISSUE TITLE
Update metaurl config by killing mount pod while keeping workloads running

### ISSUE THREAD

**Issue by fungaren** [juicedata/juicefs-csi-driver#681]
Steps:

1. Workload have set `mountPropagation: HostToContainer`
1. Change the `metaurl` in JuiceFS secret
1. Kill mount pod
1. JuiceFS CSI recreate the mount pod
1. Check the mount options of the mount pod:

```bash
kubectl get pod/juicefs-my-node-pvc-be2a6272-2e0e-4753-85b7-cdb36e6abd79-dpgqua -n kube-system -oyaml
kubectl get secret/juicefs-my-node-pvc-be2a6272-2e0e-4753-85b7-cdb36e6abd79-dpgqua-secret -nkube-system -oyaml
```

The result is that the metaurl in the secret is not changed. As [your document](https://juicefs.com/docs/zh/csi/faq#seamless-remount) said that whether the mount pod will be recreate is determined by the `GenHashOfSetting()`:

https://github.com/juicedata/juicefs-csi-driver/blob/674ac83c3324f2ec4950d65f5e8d9102cef031b9/pkg/juicefs/mount/pod_mount.go#L648-L662

It seems that we cannot change `metaurl` (or something else) in this way. So I will:

1. Change the secret `juicefs-my-node-pvc-be2a6272-2e0e-4753-85b7-cdb36e6abd79-dpgqua-secret` by hand
1. Kill the mount pod `juicefs-my-node-pvc-be2a6272-2e0e-4753-85b7-cdb36e6abd79-dpgqua`

And this way works fine. The problem is that it is really inconvenience and not straightforward. Any suggestions?

**Comment by zwwhdls** [comment]
When application pod does not restart and only mount pod restarted, the secret won't be updated. So, update `metaurl` in secret and kill mount pod, the metaurl used in mount pod will not be updated. 

The only way is restarting application pod.
