### ISSUE TITLE
[FEATURE] monolith mode

### ISSUE THREAD

**Issue by enspritz** [juicedata/juicefs-csi-driver#701]
**What feature you'd like to add:**
I'd like the CSI driver to support the CSI plugin `monolith` type, which is the combination of `controller` and `node`.

**Why is this feature needed:**
- Reduced resource usage, increased density.
- Simplified deployment, management, documentation.

**Comment by zwwhdls** [comment]
Hi @enspritz , are you referring to the concept of "monolith type" as mentioned in Nomad's documentation: https://developer.hashicorp.com/nomad/docs/job-specification/csi_plugin#csi_plugin-parameters? And Kubernetes doesn't have this mode?

**Comment by enspritz** [comment]
Yes that's right, Nomad's [`monolith`](https://developer.hashicorp.com/nomad/docs/job-specification/csi_plugin#type) type. Both controller and node at the same time. JuiceFS is the first CSI driver The current dimorphism appears to be effected in [`main.run()`](https://github.com/juicedata/juicefs-csi-driver/blob/bef5de722a3beeedc43f2c221fcc6e0ff1dbd322/cmd/main.go#L87) , dependent on `POD_NAME` envvar.
