### ISSUE TITLE
The continuous increase in storage

### ISSUE THREAD

**Issue by Zzt1993** [juicedata/juicefs-csi-driver#710]
I use the milvus installed by help and the storageClass made by juicefs. Juicefs' metadata is stored in Redis and Object storage are stored in mini

The storage size of mini has been continuously increasing in the Milvus cluster without any use

I have stored 3G for about 12 hours. Is there any good way to stop the increase
![image](https://github.com/juicedata/juicefs-csi-driver/assets/95836616/f4a86a30-01d4-4ca8-b02e-81a386580c4d)

**Comment by zwwhdls** [comment]
dup to https://github.com/juicedata/juicefs-csi-driver/issues/711. closing
