### ISSUE TITLE
The continuous increase in storage

### ISSUE THREAD

**Issue by Zzt1993** [juicedata/juicefs-csi-driver#711]
I use the milvus installed by helm and the storageClass made by juicefs. Juicefs' metadata is stored in Redis and Object storage are stored in minio

The storage size of mini has been continuously increasing in the Milvus cluster without any use

I have stored 3G for about 12 hours. Is there any good way to stop the increase
![image](https://github.com/juicedata/juicefs-csi-driver/assets/95836616/f4a86a30-01d4-4ca8-b02e-81a386580c4d)

**Comment by Zzt1993** [comment]
![image](https://github.com/juicedata/juicefs-csi-driver/assets/95836616/0bfd0f76-9b63-4f79-8089-f3084d23e70d)

**Comment by Hexilee** [comment]
Is the milvus running in the meanwhile? The data may be written by milvus, you can monitor the access log of juicefs by `cat $MOUNTPOINT/.accesslog`.

**Comment by Zzt1993** [comment]
Yes, it's running. I can't find the log file you mentioned over there. I deployed it using k8s, so do I need kubectl logs - f for the pod logs in the screenshot below
![image](https://github.com/juicedata/juicefs-csi-driver/assets/95836616/13117cab-d6eb-4282-b75c-7ff3af1fe8b2)

**Comment by Zzt1993** [comment]
Only this one reported an error
![image](https://github.com/juicedata/juicefs-csi-driver/assets/95836616/cce055c6-6c19-4539-b568-e624ad6f6fec)
All other pods are
![image](https://github.com/juicedata/juicefs-csi-driver/assets/95836616/6ab067e5-9509-4155-8569-e260ccfe8f34)

**Comment by Zzt1993** [comment]
Sorry, I understand what you're saying. Could you please help me take a look at this log
![image](https://github.com/juicedata/juicefs-csi-driver/assets/95836616/53f461fd-f249-4df0-b75d-b0aa8a6a9f63)

**Comment by Zzt1993** [comment]
I just mounted it locally. Do you need me to cat it again after a while

**Comment by Zzt1993** [comment]
I mounted it locally and saw the accesslog, but it doesn't have any extra logs. My objects and size have been increasing
![image](https://github.com/juicedata/juicefs-csi-driver/assets/95836616/f588b197-702c-4ee6-bb24-c68f63a682a9)
![image](https://github.com/juicedata/juicefs-csi-driver/assets/95836616/6bfd72e8-6a9e-49fd-9312-522ad616729a)

**Comment by Hexilee** [comment]
Hi, there are normally two reasons:
1. the application (.eg. milvus) continuously writes data to Juicefs. In this case, you should check if there are some access logs while objects are increasing.
2. if you mount Juicefs with the option `writeback`, the data will be written to local disks first, and continuously be put to object storage later.

**Comment by Zzt1993** [comment]
My Milvus is only installed and not used, which is very strange. Is there any other troubleshooting ideas provided? Thank you

**Comment by Hexilee** [comment]
> My Milvus is only installed and not used, which is very strange. Is there any other troubleshooting ideas provided? Thank you

Could you enter the Juicefs volume to check if there are unexpected files? Then you can check data leaks by `juicefs fsck $metaurl`.

**Comment by Zzt1993** [comment]
juicefs fsck $metaurl log
[fsck.zip](https://github.com/juicedata/juicefs-csi-driver/files/12238553/fsck.zip)

**Comment by Hexilee** [comment]
It seems there are many files in `.trash` of Juicefs, and some objects of them (about 3GiB) are still not uploaded to object storage.  

The mount option `writeback` is likely to cause this case, could you provide the yaml config of `storageClass`?

**Comment by Zzt1993** [comment]
Thank you for your answer. Here is my configuration file information
![image](https://github.com/juicedata/juicefs-csi-driver/assets/95836616/064a7cb6-d30a-4a1c-bff8-fa1dfea02762)

![image](https://github.com/juicedata/juicefs-csi-driver/assets/95836616/444fa10f-edb8-401d-867d-f09d2c9bbdcc)
[k8s.zip](https://github.com/juicedata/juicefs-csi-driver/files/12246099/k8s.zip)

**Comment by Hexilee** [comment]
Ok, it seems all chunks are uploaded to object storage. And there are still many files in your Juicefs volume, their chunks cost 1.3GiB capacity of storage. You can clean them as needed.

[filelist.log](https://github.com/juicedata/juicefs-csi-driver/files/12246715/filelist.log)

**Comment by Zzt1993** [comment]
[dump-2023-08-02-014356.json.gz](https://github.com/juicedata/juicefs-csi-driver/files/12256477/dump-2023-08-02-014356.json.gz)

**Comment by Zzt1993** [comment]
Can you tell if the logs are being stored based on these data

**Comment by Hexilee** [comment]
The `filelist.log` is excerpted from your `fsck.log`, and your dumped meta data also shows there are still many files in your Juicefs volume. 

So, the objects on minio are expected, please check out which application write these files and if they should be deleted.

**Comment by timfeirg** [comment]
closing stale issue.
