### ISSUE TITLE
[QUESTION] how to change pv resource limit?

### ISSUE THREAD

**Issue by sjp00556** [juicedata/juicefs-csi-driver#719]
## Question
pv's volumeAttributes is immutable, how to increase resouce limit? such as juicefs/mount-memory-limit: 1Gi  increase to 5Gi

**Comment by sjp00556** [comment]
mountOptions can be edited after pv created, so is it better to set resource limits in mountOptions?

**Comment by zwwhdls** [comment]
mountOptions is the mount parameters of JuiceFS. So far, the only way of increasing resource limit/request is to delete and recreate PV.

**Comment by sjp00556** [comment]
> mountOptions is the mount parameters of JuiceFS

yes i known it is for juicefs mount option,  because mountOptions can be modified after pv creation, so i think we can compatible limit resources by this option,  recreate dynamic pv will cause data lose and recreate is not a good way

**Comment by zwwhdls** [comment]
There has been an issue for that(https://github.com/juicedata/juicefs-csi-driver/issues/447). We will support it in the future.
