### ISSUE TITLE
[BUG] The chunk files remain in the object storage even if the PVC is deleted

### ISSUE THREAD

**Issue by kyungwan-nam** [juicedata/juicefs-csi-driver#738]
**What happened**:

The chunk files remain in the object storage even if the PVC is deleted

**What you expected to happen**:

``reclaimPolicy`` is set as ``Delete`` in the storageclass.
I expected to clean the object storage as well as the metadata.
but, the chunk files remain in the object storage.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by Hexilee** [comment]
https://github.com/juicedata/juicefs-csi-driver/pull/739#issuecomment-1711019449

> I do not recommend to execute `gc` automatically because of some reasons:
> 
> 1. `gc` will scan the whole file system, including metadata and object storage, which may be very slow.
> 2. Even if you executed the `gc` command, the chunk files may still exist in the object storage because JuiceFS enables the trash directory by default.
> 
> So, I recommend you to clean up the trash directory as necessary and run `gc` command mannelly.

**Comment by Hexilee** [comment]
Resolved in https://github.com/juicedata/juicefs-csi-driver/pull/739
