### ISSUE TITLE
[BUG] mount failed when `/sys/fs/fuse` not exist in host

### ISSUE THREAD

**Issue by zwwhdls** [juicedata/juicefs-csi-driver#744]
**What happened**:
```
Warning  FailedMount  1s (x7 over 33s)  kubelet  MountVolume.SetUp failed for volume "fuse-connections" : mkdir /sys/fs/fuse: operation not permitted
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): v0.22.0
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by fi-ecavc** [comment]
me too.
kubelet  MountVolume.SetUp failed for volume "fuse-connections" : mkdir /sys/fs/fuse: operation not permitted
