### ISSUE TITLE
Can DaemonSet hostNetwork configuration be removed?

### ISSUE THREAD

**Issue by ggaaooppeenngg** [juicedata/juicefs-csi-driver#81]
https://github.com/juicedata/juicefs-csi-driver/blob/master/charts/juicefs-csi-driver/templates/daemonset.yaml#L99, this configuration makes the juicefs host port occupied and not able to be deployed twice.

**Comment by chnliyong** [comment]
It can be removed, we'll consider this. 
What's your scenario that the _Daemonset_ has two instances on the same node?

**Comment by ggaaooppeenngg** [comment]
@chnliyong In multi tenant environment, we provide more than one juicefses.

**Comment by chnliyong** [comment]
The `juicefs-csi-driver` is not stateless, it will communicate with `kubelet` using `root-dir` host path (default `/var/lib/kubelet`) like register, share mount point etc. .

**Comment by yujunz** [comment]
> The juicefs-csi-driver is not stateless, it will communicate with kubelet using root-dir host path (default /var/lib/kubelet) like register, share mount point etc. .

This does not requires `hostNetwork`, does it? The socks are bind via `hostPath` only if I remember correctly.

**Comment by chnliyong** [comment]
> > The juicefs-csi-driver is not stateless, it will communicate with kubelet using root-dir host path (default /var/lib/kubelet) like register, share mount point etc. .
> 
> This does not requires `hostNetwork`, does it? The socks are bind via `hostPath` only if I remember correctly.

Yes. `hostNetwork` is not required. Will document it.

**Comment by yujunz** [comment]
I think we can remove it from the default deployment since it causes problems.

**Comment by zwwhdls** [comment]
fixed in https://github.com/juicedata/juicefs-csi-driver/pull/110
