### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by showjason** [juicedata/juicefs-csi-driver#826]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/juicedata/juicefs-csi-driver/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation: [JuiceFS CSI Driver Doc](https://juicefs.com/docs/csi/introduction/)

**What help did you want**:

In dashboard-ui, the access modes `ReadOnlyMany` and `ReadWriteMany` are mapped to `ROM` and `RWM`.
Why not keep consistent with the abbreviation on the [official documents](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes:~:text=In%20the%20CLI%2C%20the%20access%20modes%20are%20abbreviated%20to%3A) by mapping to `ROX` and `RWX`?

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): latest
- Kubernetes version (e.g. `kubectl version`): 1.23
- Object storage (cloud provider and region): MinIO
- Metadata engine info (version, cloud provider managed or self maintained): Redis
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): -
- Others: -

**Comment by zwwhdls** [comment]
Sorry, it's a mistake, we will fix it soon.
