### ISSUE TITLE
[OPTIMIZATION]  System namespace filter is unnecessary in system pod page

### ISSUE THREAD

**Issue by showjason** [juicedata/juicefs-csi-driver#840]
**What happened**:
From the juicefs csi deployment perspective, if my understanding is correct, there is only one system namespace, so no need to enable the system namespace filter in system pod page.
**What you expected to happen**:
disable the system namespace search in system pod page
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): latest
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zwwhdls** [comment]
closed by https://github.com/juicedata/juicefs-csi-driver/pull/841
