### ISSUE TITLE
[BUG] juicefs pvc挂载失败

### ISSUE THREAD

**Issue by moyasu** [juicedata/juicefs-csi-driver#891]
**What happened**:
在使用helm chart部署juicefs csi后，挂载pvc失败。

**What you expected to happen**:
期望挂载成功
**How to reproduce it (as minimally and precisely as possible)**:
1. csi 版本
juicefs         default         1               2024-03-07 20:20:12.476868281 +0800 CST deployed        juicefs-csi-driver-0.19.7       0.23.4

csi node pod的日志：

<img width="1899" alt="企业微信截图_1709861893168" src="https://github.com/juicedata/juicefs-csi-driver/assets/141991268/8c0dcb2e-e5f2-4cc1-97f9-8873c5166d27">

mount pod 的挂载信息：

<img width="1723" alt="企业微信截图_17098619406464" src="https://github.com/juicedata/juicefs-csi-driver/assets/141991268/97fa130a-aaa5-4494-bbdd-e8cbdc510645">

里面没有看到t /jfs/pvc-c214259a-de01-40ce-9e09-13396a0b55ae-llipzh

pvc 信息：

<img width="971" alt="企业微信截图_17098620047468" src="https://github.com/juicedata/juicefs-csi-driver/assets/141991268/740f14c7-6695-4238-a854-6b9874b7052c">
`

root@node1:~# kubectl get pvc redis-data-cvat-redis-master-0 -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: csi.juicefs.com
    volume.kubernetes.io/storage-provisioner: csi.juicefs.com
  creationTimestamp: "2024-03-07T12:22:00Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: cvat
    app.kubernetes.io/name: redis
  name: redis-data-cvat-redis-master-0
  namespace: default
  resourceVersion: "90528865"
  uid: c214259a-de01-40ce-9e09-13396a0b55ae
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: juicefs-sc
  volumeMode: Filesystem
  volumeName: pvc-c214259a-de01-40ce-9e09-13396a0b55ae
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
`

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): juicefs-csi-driver-0.19.7       0.23.4
- Kubernetes version (e.g. `kubectl version`):1.26.0
- Object storage (cloud provider and region):minio
- Metadata engine info (version, cloud provider managed or self maintained): redis  （juicefs-redis   default         1               2024-03-07 20:17:59.444772987 +0800 CST deployed        redis-cluster-9.1.3             7.2.3
）
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by timfeirg** [comment]
需要 mount pod 详细日志、events（提供完整文字） @moyasu

**Comment by moyasu** [comment]
不过mount pod的log就是上面截图这个 没有更详细的了啊 怎样获得更详细的日志呀

**Comment by zxh326** [comment]
> 不过mount pod的log就是上面截图这个 没有更详细的了啊 怎样获得更详细的日志呀

就是你图片 exec 上这个pod，发一下他的日志。

**Comment by timfeirg** [comment]
stale

**Comment by wisherx** [comment]
请问这个问题后续有进展吗？我们也有遇到相似的问题，不知道有没有什么大的思路。

**Comment by timfeirg** [comment]
「挂载失败」是一个大篮子，里边装着许许多多不同的问题，麻烦按照文档先行采集信息，然后单独记录 issue 跟进 @wisherx 

https://juicefs.com/docs/zh/csi/troubleshooting/#basic-principles

**Comment by xxiao93** [comment]
+1   我们这边也遇到过类似的问题，主要表现为  mount_pod 成功运行一段时间后，发现里面的 /jfs/xxxx 挂载点莫名消失了，导致之后的用到这个卷的 pod 都没法起来，目前看遇到的频率还挺高的，但是目前不确定到底是 juicefs 的问题还是 csi 的 bug

**Comment by zxh326** [comment]
> +1 我们这边也遇到过类似的问题，主要表现为 mount_pod 成功运行一段时间后，发现里面的 /jfs/xxxx 挂载点莫名消失了，导致之后的用到这个卷的 pod 都没法起来，目前看遇到的频率还挺高的，但是目前不确定到底是 juicefs 的问题还是 csi 的 bug

遇到问题后按文档采集下信息看看？

https://juicefs.com/docs/zh/csi/troubleshooting/#basic-principles

**Comment by xxiao93** [comment]
> > +1 我们这边也遇到过类似的问题，主要表现为 mount_pod 成功运行一段时间后，发现里面的 /jfs/xxxx 挂载点莫名消失了，导致之后的用到这个卷的 pod 都没法起来，目前看遇到的频率还挺高的，但是目前不确定到底是 juicefs 的问题还是 csi 的 bug
> 
> 遇到问题后按文档采集下信息看看？
> 
> https://juicefs.com/docs/zh/csi/troubleshooting/#basic-principles

都看过，问题不出在 k8s 这边，问题表层表现是  /jfs/xxx 这个 mount point 莫名消失了，类似执行了 umount && remove /jfs/xxxx，但是没有任何线索是谁做的这个操作(csi node recover targetPath 会存在 bug 吗？)

**Comment by zxh326** [comment]
这个挂载点是存在在 node host 上的，检察有没有其他地方使用（例如你们创建了一个 job 来做一些事情，然后结束的时候执行了 umount

另外 没有 log 等信息的话，我们什么也帮助不了你。
