### ISSUE TITLE
[BUG] default image cannot be pulled when using latest docker

### ISSUE THREAD

**Issue by h0hmj** [juicedata/juicefs-csi-driver#910]
**What happened**:

using helm to deploy csi-drive in k8s, failed to pull image

docker version:
```
# apt-cache policy docker-ce | head
docker-ce:
  Installed: 5:26.0.0-1~ubuntu.22.04~jammy
  Candidate: 5:26.0.0-1~ubuntu.22.04~jammy
  Version table:
 *** 5:26.0.0-1~ubuntu.22.04~jammy 500
        500 https://mirrors.aliyun.com/docker-ce/linux/ubuntu jammy/stable amd64 Packages
        100 /var/lib/dpkg/status
     5:25.0.5-1~ubuntu.22.04~jammy 500
        500 https://mirrors.aliyun.com/docker-ce/linux/ubuntu jammy/stable amd64 Packages
     5:25.0.4-1~ubuntu.22.04~jammy 500
```
pod stucks at pulling image `quay.io/k8scsi/livenessprobe:v1.1.0`

have tried to call docker pull directly
```
root@k8s:~/juicefs-csi-driver# docker pull quay.io/k8scsi/livenessprobe:v1.1.0
v1.1.0: Pulling from k8scsi/livenessprobe
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of quay.io/k8scsi/livenessprobe:v1.1.0 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```

**What you expected to happen**:

image pulled successfully

**How to reproduce it (as minimally and precisely as possible)**:

just use latest docker-ce and pull

**Anything else we need to know?**

according to https://docs.docker.com/engine/deprecated/#pushing-and-pulling-with-image-manifest-v2-schema-1 `Disabled by default in Release: v26.0`, so we need to upgrade the default image version maybe. 

_**it is easy to solve the problem by setting specific newer image version in yaml or downgrade docker version, but we need recommanded version and related doc maybe.**_

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): 0.23.5
- Kubernetes version (e.g. `kubectl version`): 1.23.17
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by h0hmj** [comment]
cc @zxh326 @timfeirg

**Comment by zxh326** [comment]
yeah, it's time to update the default CSI sidecar image

https://kubernetes-csi.github.io/docs/sidecar-containers.html
