### ISSUE TITLE
[FEATURE] better csi dashboard time display

### ISSUE THREAD

**Issue by h0hmj** [juicedata/juicefs-csi-driver#911]
**What feature you'd like to add:**

for example, in pages such as `/app/syspods`, `/app/pods`, etc, CreateTime is in utc +8 time zone.
<img width="1311" alt="image" src="https://github.com/juicedata/juicefs-csi-driver/assets/11989040/47288d6d-34ae-4f1d-856d-2c43c3ba4276">

but in a specific pod page, time is utc.
<img width="1082" alt="image" src="https://github.com/juicedata/juicefs-csi-driver/assets/11989040/d976ad24-45c0-4441-bd5c-fc03b72eb46d">

Values are all correct but a little bit wired. Switching between pages may cause misunderstanding. Any idea to make it better? 

**Why is this feature needed:**

**Comment by showjason** [comment]
How about convert time according to the time zone currently set by the browser? If you think it’s feasible, I’d like to fix it.

**Comment by h0hmj** [comment]
cc @zxh326 any idea?
