### ISSUE TITLE
[FEATURE] Customize the deployment of csi-node without affecting the netowrk mode of mount pod

### ISSUE THREAD

**Issue by zivgan** [juicedata/juicefs-csi-driver#914]
**What feature you'd like to add:**
Customize the deployment of csi-node daemonset with hostNetwork mode，while not affecting the netowrk mode of juicefs mountpod

**Why is this feature needed:**
Due to the limited number of IPs in the Kubernetes cluster, it is necessary to modify the juicefs-csi-node daemonset to use the hostNetwork mode. After this change, the automatically created mountpods also become hostNetwork mode, and the pod's metric port changes from 9567 to 0. However, our Prometheus data collection is done through port 9567.

**Comment by zxh326** [comment]
fixed in #938

after [v0.24.0](https://github.com/juicedata/juicefs-csi-driver/releases/tag/v0.24.0) release, you can configure mountpod with a different configuration from csi-node.
