### ISSUE TITLE
Inadequate Chinese language support

### ISSUE THREAD

**Issue by showjason** [juicedata/juicefs-csi-driver#918]
**What happened**:
Some sections or fields of dashboard are not support Chinese, for example:
SC details page
![image](https://github.com/juicedata/juicefs-csi-driver/assets/27723125/d896f96e-d324-47e0-99c8-1990bb8062fa)
There is a column is wired in SC details page, I guess it should exhibit the `createTime` of PV, but it named `startStatus`
![image](https://github.com/juicedata/juicefs-csi-driver/assets/27723125/1302de4e-0ed6-4e73-a249-df0b3945edfc)
Event details page
![image](https://github.com/juicedata/juicefs-csi-driver/assets/27723125/66b344b5-ee17-4e92-86df-12c8fa7a4c59)
PV details page
![image](https://github.com/juicedata/juicefs-csi-driver/assets/27723125/de9201ae-e402-4123-8f0d-5568ea103ff4)

Apart from the `Parameters` of SC details page, because I'm not sure if it is proper to translate it into `参数`, I fix all the others in my dev environment:
SC details page
<img width="652" alt="image" src="https://github.com/juicedata/juicefs-csi-driver/assets/27723125/bfb517a1-b972-4d92-bbfb-43733627239d">
![image](https://github.com/juicedata/juicefs-csi-driver/assets/27723125/cf374f9b-f3d6-4d14-9475-1b093c544093)

Event details page
![image](https://github.com/juicedata/juicefs-csi-driver/assets/27723125/c84c72bd-37e8-4e3f-8f89-ff4d57bdf08c)
PV details page
![image](https://github.com/juicedata/juicefs-csi-driver/assets/27723125/cac65dea-947d-4ea1-a325-faa850703146)

If you think my fix is correct, I'd like to open a PR, or please let me know which parts I should modify to better fix this issue.

**What you expected to happen**:
support Chinese as complete as possible
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): latest version
- Kubernetes version (e.g. `kubectl version`): 1.22
- Object storage (cloud provider and region): minIO
- Metadata engine info (version, cloud provider managed or self maintained): Redis
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zxh326** [comment]
Yeah, sounds great. please feel free to submit a PR

Thanks.

**Comment by showjason** [comment]
Fixed by #921
