### ISSUE TITLE
Does Dynamic provisioning support to change permission by securityContext

### ISSUE THREAD

**Issue by wutz** [juicedata/juicefs-csi-driver#92]

**Comment by chnliyong** [comment]
@wutz A little bit confused! Could you supply more details of this question? `Securtiy Context` is applied for `Pod` or `Container`, which affect the processes access the filesyste, dynamic provisioning is the process the CSI driver provisioning storage.

**Comment by wutz** [comment]
I use pvc which by juicefs storageclass to run pod as non root user by set `securtiyContext { runAsNonRoot: true, runAsUser: 1000, fsGroup: 3000}` , but got write permission denied.

Then i test to use custom `pv` to run pod as non root user, it work correctly.

**Comment by wutz** [comment]
I noticed that the examples are all about modifying mount-optinons and Permissions for static provisioning, but there is no mention of how to modify the above configuration for dynamic provisioning.

**Comment by chnliyong** [comment]
> I noticed that the examples are all about modifying mount-optinons and Permissions for static provisioning, but there is no mention of how to modify the above configuration for dynamic provisioning.

Thanks to feedback this, we'll try to reproduce this problem.
The `StorageClass` also support [mount options](https://kubernetes.io/docs/concepts/storage/storage-classes/#mount-options),  we'll verify if it works.
