### ISSUE TITLE
[BUG] csi reconciler hanging because of pod lock can not required

### ISSUE THREAD

**Issue by sjp00556** [juicedata/juicefs-csi-driver#957]
**What happened**:
场景：我们是一个业务pod挂载了多个不同的juicefs文件系统，同时业务侧会反复的创建删除pod，mount pod会被频繁的创建删除
现象：reconciler出现阻塞，卡死的现象，NodePublishVolume  出现大量的创建超时重试，mount pod 处于长时间 terminating，新的mount pod 很久才会被创建出来

**相关现场日志**
![image](https://github.com/juicedata/juicefs-csi-driver/assets/6017354/455712cf-00f7-4ab7-8a30-9f6c2e7d0c30)

E0521 10:13:27.965644       1 driver.go:85] GRPC error: rpc error: code = Internal desc = Could not mount juicefs: rpc error: code = Internal desc = rpc error: code = Internal desc = Mount root0 failed: mount pod xxx-v7-slave15-20240110.kscn-root0 has been deleting for 2 min

NodePublishVolume 出现大量的重试，阻塞了一段时间后，这些重试的请求均挂载成功了
```
I0522 01:40:12.170382       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 01:42:12.301719       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 01:44:13.324061       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 01:46:15.370284       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 01:48:19.456360       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 01:50:27.581913       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 01:52:43.612835       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 01:55:15.692866       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 01:58:19.773503       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 02:02:21.873666       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 02:06:23.936955       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 02:10:26.026481       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 02:14:28.100980       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 02:18:30.181971       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 02:22:32.198346       1 node.go:99] NodePublishVolume: creating dir /var/lib/........
I0522 02:26:34.288353       1 node.go:99] NodePublishVolume: creating dir /var/lib/........

调度阻塞

I0522 02:28:32.757529       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:32.939330       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:33.639886       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:34.840546       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:36.040262       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:37.242308       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:38.443522       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:39.646477       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:40.852038       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:42.067670       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:43.286159       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:44.529814       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:45.834245       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:47.153062       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:48.711668       1 node.go:155] NodePublishVolume: mounted xxxxxx
I0522 02:28:50.700229       1 node.go:155] NodePublishVolume: mounted xxxxxx
```

**问题复现及定位**
![image](https://github.com/juicedata/juicefs-csi-driver/assets/6017354/e377dc5c-39c9-43d1-ac90-782183bfee9a)

**时间线分析**
1. 业务pod 被删除，mount pod 被删除，mount pod 处于terminating状态
2. 业务再次创建pod，多个mount pod 被调度创建，进入NodePublishVolume 阶段，在createOrAddRef 方法里拿到了 pod lock，阻塞等待 之前旧的mount pod 退出
3. 旧的mount pod 是由 podDeletedHandler 回收掉，但是 reconciler  是每5秒调度一次的，如果reconciler在2之后才执行到对应的pod就会产生死锁等待的问题。 因为 podDriver.Run(ctx, pod) 中的 checkAnnotations 同样会拿pod lock，拿到后才会进行后面的podDeletedHandler 释放步骤，但是2步骤一直持有锁，只有到1分钟超时后才会释放pod lock，3才能拿到锁删除掉旧pod。
4. 因为我们一个业务pod调度了多个pv，导致一旦出现这种阻塞情况，reconciler卡住，后面的多个pv的NodePublishVolume出现超时重试。导致最终经过很长时间mount pod 才能被正确创建出来

**相关修复**
在createOrAddRef sleep 阶段释放锁，sleep之后加回锁，这样reconciler就能正常执行下去，就能解决reconciler被阻塞的问题。
https://github.com/juicedata/juicefs-csi-driver/pull/952

**Comment by zxh326** [comment]
呃 你这个版本多少，是不是非常老了。。

**Comment by sjp00556** [comment]
@zxh326 是的我们在0.16分支出来的版本，但是master的版本是同样有锁的问题

**Comment by zxh326** [comment]
> @zxh326 是的我们在0.16分支出来的版本，但是master的版本是同样有锁的问题

不会的，新版的拿 mountpod lock 之前，会过滤掉处于 terminate 的pod，不复用。

我建议你先升级下吧

**Comment by sjp00556** [comment]
@zxh326 我已经看了新版本了，checkAnnotations 这里的锁和 createOrAddRef 的锁会互相阻塞。辛苦再仔细看看，这里的锁是有冲突的。 createOrAddRef这里是拿着锁去检测是否是terminating，但是terminating的pod会在checkAnnotations之后podDeletedHandler 流程才会被释放的。 
![image](https://github.com/juicedata/juicefs-csi-driver/assets/6017354/c4b8a6e9-c449-4d7f-a25b-f057b40091b0)
![image](https://github.com/juicedata/juicefs-csi-driver/assets/6017354/ec9178db-7f18-47b9-a381-d32177a94982)

辛苦 @davies 帮忙review下。改动两行锁的逻辑
https://github.com/juicedata/juicefs-csi-driver/pull/952/files#diff-d03f43402bec1c945fd6a2d546c0f14b00d482f947db31115b08fba00b8f8747R332
