### ISSUE TITLE
[FEATURE] allow customizing init container resource (or provide sensible defaults)

### ISSUE THREAD

**Issue by timfeirg** [juicedata/juicefs-csi-driver#963]
**What feature you'd like to add:**
provide a sensible default resources definition for init containers (jfs-format), or provide means of customization
**Why is this feature needed:**
some kubernetes clusters use LimitRange which can potentially forbid pod creation with empty resources definition

**Comment by zxh326** [comment]
Starting from v0.23.0, we no longer use initcontainer

https://github.com/juicedata/juicefs-csi-driver/commit/4106e83f7f4d939f48248719f42de6741d287db7

https://github.com/juicedata/juicefs-csi-driver/issues/756
